### ISSUE TITLE
Rename Unknown language to English

### ISSUE THREAD

**Issue by ajhorvath20** [Casvt/Plex-scripts#1]
Hi, loving your scripts.

Maybe its too much to ask but is it possible to rename audio to English where its displayed as Unknown? 

I have media on cloud so I cannot use any conversion software like mkvedit or tdarr. 

I hope you might be able to come up with something. 

Let me know please if you need more information. 

Thank you

**Comment by Casvt** [comment]
You can show subtitles as languages using the following (natively supported by Plex):
sub.srt -> unknown
sub.en.srt -> English
sub.it.srt -> Italian
Etc.

**Comment by ajhorvath20** [comment]
Hi @Casvt thank you so much for looking into this for me. Yes you are right thats what I am doing with subtitles but I just cannot find a way to do it with audio language. 

![image](https://user-images.githubusercontent.com/65309559/131260699-0ef68ee1-fc69-466e-8329-03f4e4630c14.png)

**Comment by Casvt** [comment]
There is no way to do this without changing the metadata inside the file with a tool like mkvtoolnix. Because you mentioned that you can't use tools like those, it's not possible.
