### ISSUE TITLE
Sonarr_refresh_tba: Support for refreshing in Plex

### ISSUE THREAD

**Issue by lamepennies** [Casvt/Plex-scripts#101]
Just like the TBA Sonarr scanner, would be nice to refresh metadata for TBA named episodes in Plex.

**Comment by Casvt** [comment]
Will be implemented as a feature into the existing script.

**Comment by lamepennies** [comment]
Just to also flag, on the series Loot, instead of TBA it's TBD.

**Comment by Casvt** [comment]
I'm sorry, what do you mean with "on the series Loot"?

**Comment by lamepennies** [comment]
In Sonarr, I have a series called "Loot" and instead of it listing **TBA** for episodes names, it says **TBD**.

**Comment by Casvt** [comment]
Apprrently it means "to be determined" and thus means exactly the same as "TBA". I'll include it in the script.

**Comment by Casvt** [comment]
Request completed. Please redownload the script to get the new feature: https://github.com/Casvt/Plex-scripts/blob/main/sonarr/sonarr_refresh_tba.py

When choosing plex, it will go through every episode on your server and all episodes that have 'tba' or 'tbd' as the title will get their metadata refreshed. Enjoy!

**Comment by lamepennies** [comment]
Oh really cool. I'm having issues with it triggering plex to refresh the meta for the episodes. It's listing 3 eps with the TBA/TBD but it isn't triggering a refresh. Same thing with sonarr just listing and not triggering a refresh. 

I've flagged it in this ticket: https://github.com/Casvt/Plex-scripts/issues/116
