### ISSUE TITLE
Keyword to Genre List For ALL Folders

### ISSUE THREAD

**Issue by bigverm23** [Casvt/Plex-scripts#106]
In what file should the feature be added?
keywords_to_genre.py 
What is the feature request?
ability to add keyword to genre list for ALL library folders vs individual (ex. movies or tv shows)

**Comment by bigverm23** [comment]
currently I can only run the script for a single library at a time ex. "Movies"

I'd like to run the script for ALL plex libraries in a single command - multiple libraries at the same time

**Comment by Casvt** [comment]
Oh alright that's easy to do

**Comment by bigverm23** [comment]
another question, does this script auto genre for media as it's added or does it need to be run more than once as new media comes in?

**Comment by Casvt** [comment]
It does it with the current media. That means that when you add new media, you need to run the script again to process the new media.

**Comment by Casvt** [comment]
Request completed. You can now pass the `--LibraryName` multiple times to process multiple libraries at the same time.
