### ISSUE TITLE
auto_upgrade_media.py: downgrade after viewcount

### ISSUE THREAD

**Issue by Chewwwy92** [Casvt/Plex-scripts#119]
If you have a movie that is a 4k REMUX or a Tv show that is 4k it would be awesome to delete it once it has been watched. so I still have the content but its not taking up as much space.

**Comment by Casvt** [comment]
Isn't this already possible in Plex? See https://i.imgur.com/DCikEjn.jpg.

Those settings can be used to set it up.

**Comment by Chewwwy92** [comment]
But could that then trigger sonnar to re-download at a lower quality? Otherwise sonnar would most likely just re-download it at the current quality

**Comment by Casvt** [comment]
It's smarter to make this a feature for this script: https://github.com/Casvt/Plex-scripts/blob/main/media_versions/auto_upgrade_media.py

**Comment by Casvt** [comment]
Request completed. Feature added to this script: https://github.com/Casvt/Plex-scripts/blob/main/media_versions/auto_upgrade_media.py

Use `--DowngradeAboveViewcount 1` to downgrade media after it has been watched once.

Little note: I'm going to significantly upgrade/improve this script soon so you might want to wait on that one so you use the nice version. The current version (though it works) is not well written and has some small bugs. I advice you to wait. I'll let you know when the upgrade is completed.

**Comment by Casvt** [comment]
Upgraded the script. Enjoy \:\)
