### ISSUE TITLE
How to get the plex_api_token?

### ISSUE THREAD

**Issue by Heisenberg2980** [Casvt/Plex-scripts#121]
I just found this repo with scripts for plex, what a great idea!!
I just have one question, could some instructions be added to the main readme file explaining how to get the plex_api_token?

**Comment by Casvt** [comment]
Info can already be found in the [wiki](https://github.com/Casvt/Plex-scripts/wiki/Setup#variables).

**Comment by Heisenberg2980** [comment]
> Info can already be found in the [wiki](https://github.com/Casvt/Plex-scripts/wiki/Setup#variables).

You are totally right, I should have checked there, thanks!!
