### ISSUE TITLE
Sync Item Posters between two local libraries

### ISSUE THREAD

**Issue by HStep20** [Casvt/Plex-scripts#124]
It would be great to have a script that would sync the posters between two libraries. The need mostly comes from users who have separate 4k and Standard libraries where 4k library is a subset of items found in the standard library. If we could define a directional relationship between libraries, it could copy all of the posters from 'Item x' of Library A to 'Item x' of Library B. 

It would keep a unified look across the server, and cut down on managing posters, since you could set posters in Library A and replicate them to Library B

**Comment by Casvt** [comment]
Already exists: https://github.com/Casvt/Plex-scripts/blob/main/various/plex_library_sync.py

Take notice of this bug though: https://github.com/Casvt/Plex-scripts/issues/53

Try it out and see how it goes!
