### ISSUE TITLE
Collection Creation

### ISSUE THREAD

**Issue by JPH71** [Casvt/Plex-scripts#128]
Would it be possible for you to create a script that does the following:
- Create a Collection
- Allow one to either point to an image on disk or to a url. This image will be the collection poster
- Allow another image for the background
- Allow one to imput text to describe the collection
- Create as standard collection or smart collection.
I could then run it from DOS:
C:\python CreatePlexCollection.py Name:xxx SortName:xxx Poster:xxx Art:xxx Text:xxx.txt Type:Standard|Smart

Cheers

**Comment by Casvt** [comment]
So you basically want to create collections from the command line haha. Sure

**Comment by JPH71** [comment]
Yes please....
I hope its not too difficult..
I have been looking in the database to see where it stores everything but
can't seem to find where all the information is stored...
And databases are confusing and if you make a mistake... oops to
everything...

**Comment by Casvt** [comment]
It's fairly easy to do with the api of Plex. Just get all the values of the things that you want and then send a request to Plex with all of them in it and done. No database interaction needed. Don't worry.

**Comment by JPH71** [comment]
I have never used the plex api...

I have looked at plex agent scripts.. I an see how they create collections,
but they only use a string... so no pictures or summaries...

Would it be possible for you to give a short demo script on how to use the
plex app?

**Comment by Casvt** [comment]
You'll just have to wait until my script is completed. It's going to work like this:

1. The user gives all the arguments (e.g. `-t test -s 0 -p https://poster.com/poster -S 'this is a summary'`)
2. We create the collection, giving the title and smart value as arguments. This will create the collection in plex.
3. Then, if a value for the poster is given: if the value is a file path, get the content of the poster file and make a new request where we change the poster. If the value is a URL, we make a new request where we parse the URL and Plex will handle it.
4. Step 3 repeated but then for the background.
5. If there are values given to either the summary or the sort title, make a request to edit the collection, where we parse the new value of the summary or sort title (or both).

And that's it. That's exactly what the script is going to do.

**Comment by JPH71** [comment]
Nice one...

Thank you so much...

I started yesterday, but walked right into a wall as there is not much
information out there on the fields that need to be set...

Kind regards

Jason

**Comment by Casvt** [comment]
Script request completed. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/playlist_collection/create_empty_collection.py

You can create "dumb" empty collections with this script. Run the script with "-h" to see what arguments you need to give.

**Comment by JPH71** [comment]
Wow! Thanks, I will check it out!

**Comment by JPH71** [comment]
Hi Again

I think I have found it - with this bit of code:
metadataURL = '
http://127.0.0.1:32400/library/metadata/{0}?X-Plex-Token={1}'.format(metadata.id,
PLEXTOKEN)

This gets you to the view xml option....
The library name is
However, does this mean it is only available after the media item has been
scraped and how much time should one wait before this file is populated
with the just scraped contents.....

**Comment by Casvt** [comment]
To be honest, I don't have a single clue what you're talking about. I'm not following you at all here.

Something with scraping? My script doesn't have anything to do with scraping? You need to give a bit more context.

P.S. good formatting of your comments helps a lot. There are a lot of random enters, left out words and barely any comma's. That makes it harder to understand what you mean.

**Comment by JPH71** [comment]
The script is brilliant especially since I do not have to import the
plex-api library.
two questions.
1. Once I have created a collection - how do I add members to it?
2. If I run the script twice it creates another collection with the same
name - how do I check that a collection has already been created? So that I
can just add members to it.

Kind Regards

Jason

**Comment by Casvt** [comment]
> 1. Once I have created a collection - how do I add members to it?

Collections are in a library. Everyone that has access to the library can also view the collection. After all, a collection is just an advanced  "folder" in your Plex library.

> 2. If I run the script twice it creates another collection with the same name - how do I check that a collection has already been created?

I can fix that. So that when you add a collection that already exists, it will replace the old one with the new one.

**Comment by JPH71** [comment]
Hi there,

When I add a collection in the normal way metadata in a plex scrapping
agent:
        try:
            for idx, item in enumerate(listCollections, start=1):
                metadata.collections.add(item)
                log('UTILS :: {0:<29} {1}'.format('{0}'.format('Adding
Collections' if idx == 1 else ''), '{0:>2} - {1}'.format(idx, item)))


It does not seem to add it to the collection created by your script - hence
question number 1.

For question2 as the first collection is empty - how do i add members to
the collection.... that is the main thing I need to do.

Sorry for giving you a lot of problems.... but the issue would be solved by
me adding members to the new collection - if there was a way of getting the
new_RatingKey and adding a film/movie to it....

Kind Regards

Jason

**Comment by JPH71** [comment]
I had a small typo...
It now links the collections created to the empty collections created by
your code.
The only issue is that I get a new created collection everytime I run your
code.

If you could help with this, it would be perfect as the code as it stands
is working beautifully...

**Comment by Casvt** [comment]
Yeah sure. I'll let you know when I've updated the script.

**Comment by Casvt** [comment]
Script has been updated. If you parse `--DeleteExisting` to the script arguments, it will delete all existing collections with the same name before adding the new one.

**Comment by JPH71** [comment]
You are an absolute star!

**Comment by JPH71** [comment]
Hi
I have tried the new script and it works!
Only issue is that once it deletes the collection and recreates, media that
belongs to the collection locks the collection as in the picture below
[image: image.png]

So all that is needed is to be able to access this and unlock this field so
that I can add the recreated collection after it has been deleted.
I know that once a collection is deleted all media that are linked to the
collection will have the field locked.
However if one can unlock the media being refreshed that would help solve
the issue.... but maybe what would be better would be the ability to just
update the previously created collection so that this does not happen.

Is there a way one can update it without deleting it???

Kind Regards and sorry for been such a nuisance....

Jason

**Comment by Casvt** [comment]
I can't view the picture

**Comment by JPH71** [comment]
Hi Again,

Thank you once again for all the help, the code is working well, its been creating the collections.
How would I add a media file to link it to the empty collection as What I do now is is run the command 
metadata.collections.add(**title**)

I then use this **title** as the input variable to your code and after I run your code it creates a collection with members
This works most of the time, but over the past couple of days after the collections have been run, I have some collections with 0 items... I am using your code within a metadata agent. Collections based on Actors, Genres are scraped then passed to your code to create the collections...

Is there a way to create a collection with the film path linked to it  - so that when you click on the pen (Edit) then Info - you can see the files listed....
