### ISSUE TITLE
Feature Request: Plex_exporter_importer

### ISSUE THREAD

**Issue by RBeatse** [Casvt/Plex-scripts#14]
Make the script faster

**Comment by Casvt** [comment]
Second update has been made. You can use the link above again. 
### _**Importing is now 400% FASTER!!!**_
Take note of the new requirement listed at the top of the file. And no this isn't a joke; I've actually made importing 4 times as fast.

**Comment by Casvt** [comment]
Third update has been made. You can use the link above again.
_**Exporting is now 160% FASTER**_

**Comment by Casvt** [comment]
I've improved both importing and exporting so not much I can do anymore. I'm going to close this issue :) bye bye
