### ISSUE TITLE
poster_exporter_importer.py does not start?

### ISSUE THREAD

**Issue by gitttt54** [Casvt/Plex-scripts#145]
I'm using a Debian 11.4 VM on an Unraid host.

**In which file is the bug?**
poster_exporter_importer.py

**Describe the setup (arguments and their values, how it was run, etc.):**
I start the script via

`user@DebianCLI:~$ python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" --AllMusic -l "Hörbücher" -A "Die drei !!!"`
to import album posters with filename "cover_front.jpg" to the specific artist "Die drei !!!" in the library named "Hörbücher".

**Describe what the bug is:**
I get this result
```
python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" --AllMusic -l "Hörbücher" -A "Die drei python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t import -p poster -P cover_front.jpg --AllMusic -l Hörbücher -A "Die drei /mnt/user/appdata/skripte/poster_exporter_importer.py -t import -p poster -P cover_front.jpg --AllMusic -l Hörbücher -A "Die drei /mnt/user/appdata/skripte/poster_exporter_importer.py -h!"!"!"
usage: poster_exporter_importer.py [-h] -t {export,import} -p {poster,background} [-E] [-P POSTERNAME] [-B BACKGROUNDNAME] [-a] [--AllMovie] [--AllShow] [--AllMusic] [-l LIBRARYNAME] [-m MOVIENAME] [-s SERIESNAME] [-S SEASONNUMBER]
                                   [-e EPISODENUMBER] [-A ARTISTNAME] [-d ALBUMNAME]
poster_exporter_importer.py: error: unrecognized arguments: drei /mnt/user/appdata/skripte/poster_exporter_importer.py
user@DebianCLI:~$
```

**Describe what _should_ be happening:**
The script should start its work ;-)

**Comment by Casvt** [comment]
`--AllMusic` isn't needed because you're specifying something more specific (an artist in a library) while `--AllMusic` is to target all music libraries.

But for the rest... It should work. But it doesn't...

Try using single quotes instead of double

**Comment by Casvt** [comment]
Oh wait don't you notice something here:?
```Shell
python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" --AllMusic -l "Hörbücher" -A "Die drei python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t import -p poster -P cover_front.jpg --AllMusic -l Hörbücher -A "Die drei /mnt/user/appdata/skripte/poster_exporter_importer.py -t import -p poster -P cover_front.jpg --AllMusic -l Hörbücher -A "Die drei /mnt/user/appdata/skripte/poster_exporter_importer.py -h!"!"!" 
usage: poster_exporter_importer.py [-h] -t {export,import} -p {poster,background} [-E] [-P POSTERNAME] [-B BACKGROUNDNAME] [-a] [--AllMovie] [--AllShow] [--AllMusic] [-l LIBRARYNAME] [-m MOVIENAME] [-s SERIESNAME] [-S SEASONNUMBER]
                                   [-e EPISODENUMBER] [-A ARTISTNAME] [-d ALBUMNAME] 
poster_exporter_importer.py: error: unrecognized arguments: drei /mnt/user/appdata/skripte/poster_exporter_importer.py 
user@DebianCLI:~$
```
Doesn't the first line here seem a little long? ;)
I don't know what happened but you're executing a merge of the same command 8 times or something.

**Comment by Casvt** [comment]
Ah wait. The `!` in a shell is replaced by the last command (no kidding). The `!!!` in the command messes it up.

Simple solution: use single quotes (`'Die drei !!!'`) instead of double (`"Die drei !!!"`).

**Comment by gitttt54** [comment]
Thank you,

I now started the script via (changes double quotes with single quote)
`python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t import -p poster -P cover_front.jpg -l 'Hörbücher' -A 'Die drei !!!'`
and it now (seems to) throw the same errors as in [poster_exporter_importer.py does not start? Too much errors to identify the problem (for me). #146 ](https://github.com/Casvt/Plex-scripts/issues/146)

So that particular problem with the expanding `!` via shell seems to be solved,

but what do users have to do, if the Artist or Album name contains `'`, like `what's up, pussycat?`

**Comment by Casvt** [comment]
> but what do users have to do, if the Artist or Album name contains `'`, like `what's up, pussycat?`

Everything surrounded by single quotes are taken literally (so their special meaning is ignored). Otherwise, escape the character by adding a `\` in front like `\!`.

See the examples below. All these are taken literally due to either single quotes or escaped characters.
```
'Wow!'
"Wow\!"
"What's up?"
'What\'s up?'
"Wow\! What's up?"
'Wow! What\'s up?'
```

**Comment by gitttt54** [comment]
> See the examples below. 

That is all crazy stuff... No wonder, everyone likes a GUI.

Still in 2022 you have to deal with such cumbersome *nix stuff from the 70s ... crazy...just crazy 8->

Thanks anyway for telling and helping!!! Very appreciated!
