### ISSUE TITLE
 poster_exporter_importer.py: connection closed without response (python3.9?).

### ISSUE THREAD

**Issue by gitttt54** [Casvt/Plex-scripts#146]
I'm using a Debian 11.4 VM on an Unraid host.

**In which file is the bug?**
poster_exporter_importer.py

**Describe the setup (arguments and their values, how it was run, etc.):**
 I start the script via

`user@DebianCLI:~$ python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" --AllMusic -l "Musik" -A "The XX"`

**Describe what the bug is:**
I get this and have no clue, what the problem is? Way too many lines of confusing messages to me ;-/

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/user/appdata/skripte/poster_exporter_importer.py", line 303, in <module>
    response = poster_exporter_importer(
  File "/mnt/user/appdata/skripte/poster_exporter_importer.py", line 137, in poster_exporter_importer
    sections = ssn.get(f'{base_url}/library/sections').json()['MediaContainer'].get('Directory',[])
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
user@DebianCLI:~$
```

**Describe what _should_ be happening:**
Simple error message, which users can understand 8-}

**Comment by Casvt** [comment]
I don't know yet what's causing it but I do know that the source of the problem is Plex and not my script.

**Comment by Casvt** [comment]
What happens when you run the script using python3.8? Just run the exact same command but replace `python3` at the beginning with `python3.8`. 

The script is making a request to Plex which is very regular and has been done hundreds of times by other users of this project. The only thing I see the differentiates you from the rest is that you use python3.9. For Linux, this is newer than the default python install and very few people have it. Maybe something changed between 3.8 and 3.9 that makes it not work?

Btw, the error means that we made a connection to Plex but Plex closed the connection without ever responding. This can be both caused by the script or Plex.

**Comment by gitttt54** [comment]
> What happens when you run the script using python3.8? Just run the exact same command but replace `python3` at the beginning with `python3.8`.

Unfortunately, there is no `python 3.8`, I just see `python` and `python3.9` in the path.
I'll try to investigate how to do that on debian

btw: the server is set to REQUIRE secure connections, like here:
<img width="974" alt="sec" src="https://user-images.githubusercontent.com/96403800/189004560-4814759c-7cc6-44ca-ac03-8f1c7c6dba10.png">

I can change that on my testing server, but can not change it on the productive server.

Changing the secure connection (on my test server) to PREFERRED, seems to help the script starting, 
but now it shows another strange message, which I post in the next post.

**Comment by Casvt** [comment]
> btw: the server is set to REQUIRE secure connections, like here:

At line 24 inside the file, change `http` to `https` and see it it helps.

**Comment by gitttt54** [comment]
Starting the script via 
`python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" --AllMusic -l "Musik" -A "The XX"`

shows
```
Hörbücher
usage: poster_exporter_importer.py [-h] -t {export,import} -p {poster,background} [-E] [-P POSTERNAME] [-B BACKGROUNDNAME] [-a] [--AllMovie] [--AllShow] [--AllMusic] [-l LIBRARYNAME] [-m MOVIENAME] [-s SERIESNAME] [-S SEASONNUMBER]
                                   [-e EPISODENUMBER] [-A ARTISTNAME] [-d ALBUMNAME]
poster_exporter_importer.py: error: Artist not found
```

which seems odd to me, because `Hörbücher` is not the library, I specified.

I guess (with your kind help from the other [issue](https://github.com/Casvt/Plex-scripts/issues/145#issuecomment-1240013750)) I'll have NOT to specify `--AllMusic` AND `-l` OR `-A` alltogether. 

Can you please, for other users and for the sake of an understandable error, catch that and give the user a warning message that those options are incompatible?

**Comment by Casvt** [comment]
Remove `--AllMusic` from the arguments. It's messing up the script. I'll add an error for it tomorrow.

**Comment by gitttt54** [comment]
> At line 24 inside the file, change `http` to `https` and see it it helps.

Changed the line 24 to `base_url = f"https://{plex_ip}:{plex_port}"`

Now, I got errors like that via starting the script with 
`python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" -l "Musik" -A "The XX":`

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 464, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 512, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.9/ssl.py", line 420, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname '192.168.178.243' doesn't match '*.4eb4111111111145a4abfdaead92942e.plex.direct'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.178.243', port=32400): Max retries exceeded with url: /library/sections?X-Plex-Token=Dxsa_111111ZPdMXg5u (Caused by SSLError(SSLCertVerificationError("hostname '192.168.178.243' doesn't match '*.4eb4111111111145a4abfdaead92942e.plex.direct'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/user/appdata/skripte/poster_exporter_importer.py", line 303, in <module>
    response = poster_exporter_importer(
  File "/mnt/user/appdata/skripte/poster_exporter_importer.py", line 137, in poster_exporter_importer
    sections = ssn.get(f'{base_url}/library/sections').json()['MediaContainer'].get('Directory',[])
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.178.243', port=32400): Max retries exceeded with url: /library/sections?X-Plex-Token=Dxsa_111111ZPdMXg5u (Caused by SSLError(SSLCertVerificationError("hostname '192.168.178.243' doesn't match '*.4eb4111111111145a4abfdaead92942e.plex.direct'")))
```

The token I get via [Plex Support Pages](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/).

**Comment by Casvt** [comment]
Alright so that didn't work. Replace https back to http on line 24. Try again

**Comment by Casvt** [comment]
Is it working now?

**Comment by gitttt54** [comment]
> Replace https back to http on line 24. Try again

On my test server, I switched from REQUIRED to PREFERRED, so http will work.
(please remember, I can not change that setting on the productive server)


Yippie (without Yeah) !

It looke that way before:
<img width="1143" alt="before" src="https://user-images.githubusercontent.com/96403800/189008701-ccb6c3ba-f695-4c4c-b153-053a11baddef.png">

I started it in 2 ways (with .jpg and without, because its not clear to me from the help, which is correct, please tell)

```
user@DebianCLI:~$ python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front.jpg" -l "Musik" -A "The XX"
Musik
user@DebianCLI:~$ python3 /mnt/user/appdata/skripte/poster_exporter_importer.py -t "import" -p "poster" -P "cover_front" -l "Musik" -A "The XX"
Musik
user@DebianCLI:~$
```
Its not clear, what happened. Very less output.

I wished some more informative output like:
_processed libraries: Musik
added 2 images to 2 albums
7 albums not processed_ (if so)

I reloaded (without cache) the plex page in the browser

and now it looks like this:
<img width="1126" alt="after" src="https://user-images.githubusercontent.com/96403800/189008897-9f3a6f7d-3050-47c2-ae5f-1a0f29b123c7.png">

does your script only do albums? no singles/eps?

**Comment by Casvt** [comment]
So it's working now.
> On my test server, I switched from REQUIRED to PREFERRED, so http will work.
(please remember, I can not change that setting on the productive server)

I think it'll work even with it on REQUIRED. But I'm not sure. Try it out.

> I started it in 2 ways (with .jpg and without, because its not clear to me from the help, which is correct, please tell)

Give it without the extension.

> does your script only do albums? no singles/eps?

I thought I added support for singles/EPs too but apparently not. Though it's not that hard to add :)

**Comment by gitttt54** [comment]
> So it's working now.

Nope, no really :-)

> > On my test server, I switched from REQUIRED to PREFERRED, so http will work.
> > (please remember, I can not change that setting on the productive server)
> 
> I think it'll work even with it on REQUIRED. But I'm not sure. Try it out.

I already tested it the last hour and all the error messages are in my posts above (and how I started the script).
It does not help to change http to https inside the script (if so, that should be an option in the script)
it does not work, if REQUIRED is set up in Plex networking
it seems, the script can not handle SSL correctly (my guess)


> > I started it in 2 ways (with .jpg and without, because its not clear to me from the help, which is correct, please tell)
> Give it without the extension.

Ah, thanks! That should be stated in the scripts help.

> > does your script only do albums? no singles/eps?

> I thought I added support for singles/EPs too but apparently not. Though it's not that hard to add :)

I'll wait then, for an update to test it again.
Thank you ;-)

**Comment by Casvt** [comment]
In order to use HTTPS, set the base url to the plex direct url. It looks something like this:

```
https://{PUBLIC IP WITH DASHES}.{MACHINE ID}.plex.direct:{PUBLIC PORT}
https://12-34-5-67.123456789123456789abcdefghij123.plex.direct:12345
```
