### ISSUE TITLE
Readarr - Auto convert on import (Or scheduled Converting)

### ISSUE THREAD

**Issue by Chewwwy92** [Casvt/Plex-scripts#151]
Readarr and Calibre can convert files but you cant set it up to automatically do it on import or schedule it.

There are so many people asking for this, in forums etc. 

A lot of people want to be able to convert to either Kepub or AZW3.

**Comment by Casvt** [comment]
So basically: when a file is imported or downloaded, trigger the file conversion feature of readarr for it

**Comment by Chewwwy92** [comment]
Yeah it may also need to be added as a plugin for calibre cause some people use calibre as the main database for readarr
