### ISSUE TITLE
intro_skipper.py: Unknown client name

### ISSUE THREAD

**Issue by friedcpu** [Casvt/Plex-scripts#160]
In which file is the bug? intro_skipper.py

Describe the setup (arguments and their values, how it was run, etc.):
./intro_skipper.py -i
Describe what the bug is:
The script tries to skip to the chapter but complains about unknown client
Describe what _should_ be happening:
skip to the intro chapter as designed.

I have tried different tokens, from preferences.xml, web client xml and windows client xml, and tried to play with iphone, windows and web client and it always returns.

> [23:43:01 21-10-2022][INFO] Moving stream playing on DESKTOP-DANH1M5 to 0:38
[23:43:01 21-10-2022][ERROR] Failed:
Traceback (most recent call last):
  File "/home/friedcpu/intro_skipper.py", line 52, in move
    plex.client(player).seekTo(time, mtype='video')
  File "/usr/local/lib/python3.9/dist-packages/plexapi/server.py", line 428, in                                                      client
    raise NotFound(f'Unknown client name: {name}')
plexapi.exceptions.NotFound: Unknown client name: DESKTOP-DANH1M5

**Comment by mariosemes** [comment]
As mdhiggins mentioned in his notice [here](https://github.com/mdhiggins/PlexAutoSkip):

`Plex has recently removed the "advertise as player" feature from the Plex Web client as well as its desktop clients for Windows/Mac/Linux which breaks the PlexAutoSkip functionality. All other players that have Plex Companion continue to work normally. I'm unclear why this feature which has been stable and present for years was removed without warning from this small subset of players, but the patch notes can be found [here](https://forums.plex.tv/t/plex-for-mac-windows-and-linux/446435/63) and [here](https://forums.plex.tv/t/plex-web/20528/389).`

anyway, if you find a way to handle this without the usage of the clients, that will be a MINDBLOWN success for the community :)

Good luck! <3

**Comment by Casvt** [comment]
Well no. There's no way to do it without controlling the client. So that's issue resolved :)
