### ISSUE TITLE
Plex Music Playlist Management

### ISSUE THREAD

**Issue by samcro1967** [Casvt/Plex-scripts#161]
I see an import script `m3u_to_playlist.py`, but not an export script `playlist_to_m3u.py`.  Is there another script I am missing that can do this or is this something you could create?

**Comment by Casvt** [comment]
I think I can create that yeah

**Comment by samcro1967** [comment]
Would be greatly appreciated.  I prefer to manage playlists outside of applications and run scripts to import/export them to keep them in sync across applications.  Also like to be able to have backups of them in case something happens so that the time spent creating them is not lost.  This is what has kept me from using Plex as my main Music player platform.  I see several other scripts I am going to give a try also.  Thanks for your work!

**Comment by Casvt** [comment]
Could you tell me what scripts you're interested in? I'm trying to get an idea of the more popular and less popular scripts in this repo...

**Comment by samcro1967** [comment]
`postcreditscene_notification.py` will be the next one I check out.  No more Googling to see if a movie has one or skipping thru the credits.  Also want to try `intro_marker_editor.py`.  Would love to skip movie intros and get right to the movie.  Haven't looked at all of them yet in detail, but these 3 jumped out at me right away.

**Comment by Casvt** [comment]
intro_market_editor.py doesn't support movies yet but I'm planning on adding that :)
