### ISSUE TITLE
Help with m3u_to_playlist.py

### ISSUE THREAD

**Issue by samcro1967** [Casvt/Plex-scripts#162]
I am able to run it successfully and am not getting any errors.  I see in the plex logs that the request was completed, but the playlist is not showing up in Plex.  I optimized the Plex database and restarted Plex as well.  I also tired it in an incognito browser to rule out any browser cache issues.   Plex server is version 1.29.1.6316.  I don't see any setting in Plex to enable/hide/filter out playlists.  Guessing maybe there is a setting somewhere in Plex to allow it to be displayed?

Any ideas?

Logs
```
Request: [192.168.1.104:41666 (Allowed Network (Subnet))] POST /playlists/upload?sectionID=7&path=%2Fmnt%2Fnas%2Fxbmc%2FMusic%2FPlaylists%2FCountry.m3u (15 live) #4182 GZIP Signed-in Token (username) (Chrome) / Accept => application/json / Accept-Encoding => gzip, deflate / Connection => keep-alive / Content-Length => 0 / Host => 192.168.1.104:32400 / User-Agent => python-requests/2.25.1 / X-Plex-Token => xxxxxxxxxxxxxxxxxxxx
Completed: [192.168.1.104:41666] 200 POST /playlists/upload?sectionID=7&path=%2Fmnt%2Fnas%2Fxbmc%2FMusic%2FPlaylists%2FCountry.m3u (15 live) GZIP 0ms 195 bytes (pipelined: 2)
```

**Comment by Casvt** [comment]
I'm pretty certain that the script works.

Is the m3u file corrupted maybe?
Are all files listed in the m3u file also added in Plex?
Maybe try it with a different library selected?
Or maybe Plex removed the feature to do this (but I doubt that)?

**Comment by samcro1967** [comment]
>Is the m3u file corrupted maybe?

I am able to import the playlist into Navidrome and it plays with no issue so I don't think it is corrupted.   

>Are all files listed in the m3u file also added in Plex?

The files have been imported to Plex and I am able to play them in Plex.  The path looks correct to me.  The path in Plex to one of the songs in the m3u example below is `/music/Walker Hayes/Country Stuff The Album/Walker Hayes - AA.mp3`.

>Maybe try it with a different library selected?

I tried it with another playlist and it did not work either.

Looking at the m3u file in a text editor, it look like Navidrome is adding stuff to the file.  Maybe that is causing the issue.  Here is a sample:

**m3u example**
```
#EXTM3U
#EXTINF:193,Joe Nichols - Good Day for Living
/music/Joe Nichols/Good Day for Living/Joe Nichols - Good Day for Living.mp3
#EXTINF:212,Toby Keith - Oklahoma Breakdown
/music/Toby Keith/Peso in My Pocket/Toby Keith - Oklahoma Breakdown.mp3
#EXTINF:158,Dean Brody - Can't Help Myself
/music/Dean Brody/Boys/Dean Brody - Can't Help Myself.mp3
#EXTINF:190,Walker Hayes - AA
/music/Walker Hayes/Country Stuff The Album/Walker Hayes - AA.mp3
```

**Comment by samcro1967** [comment]
I created a small test.m3u with just a few files with none of the extended data and it is not showing up after importing so it does not look like it is the extended data.

**Comment by Azuriye** [comment]
Hello! same here. I tried making a playlist within fb2k and exporting it as .m3u8 (tried with .m3u as well) both didn't work I've checked up the HTTP requests through Wireshark and my server gives an HTTP/1.1 200 OK request indicating everything went fine but upon looking in Plex I cannot see the changes or even the playlist added in through.

**Comment by Casvt** [comment]
Maybe Plex removed the feature... I don't know.
