### ISSUE TITLE
Rewatch the previous episode of a show when a new episode releases so that the show appears at the front of "continue watching"

### ISSUE THREAD

**Issue by guaxamole** [Casvt/Plex-scripts#170]
In what file should the feature be added?
media_management 

What is the feature request?
I wanted to see if it's possible to create a script that looks for the latest episode added to Plex and takes that episode number and subtracts one to find the previous episode. Then it marks this previous episode as unwatched, and re-marks it as watched. That way, if this script is run automatically through Tautulli or another platform, every time a new episode releases, the show will be moved to the front of "continue watching." Hopefully you can work something out with this, thanks!

**Comment by guaxamole** [comment]
Thanks for accepting the request!! I just realized that it also needs to have a conditional that only allows this to run if the previous episode was watched. Without that, then episodes will be marked even if you haven't watched them yet. Not sure if that's possible or not so let me know. Thanks again!

**Comment by Casvt** [comment]
When a new episode of a series comes out, it automatically pops up again on the on-deck. So no need for a script? Maybe this behaviour was added in just the last year?
