### ISSUE TITLE
Add option to only sync smart collections in plex_sync.py

### ISSUE THREAD

**Issue by gitttt54** [Casvt/Plex-scripts#181]
Hello,

I have read the header of the script and it seems not possible, hence the request:

**In what file should the feature be added?**

plex_sync.py

**What is the feature request?**

Please let the user select, to only sync smart collections OR normal collections.

Example:
`python3 plex_sync.py --SourceName 'Batman server' --TargetName 'Robin server'  --Sync Smart-Only-Collections`

Reason:
I want to sync smart collections only from Server Batman to Server Robin.
Server Batman has abut 3000 collections, 100 are smart. Those are the ones, which are needed on Server Robin.

To NOT have to remove all 2900 normal collections from Server Robin after sync with Server Batman,
it would be great if I could select smart collections only in the script.

Is this possible?

Thank you! (And happy new Year too!)

**Comment by Casvt** [comment]
The script doesn't handle smart collections. IIRC, it's not really possible to port them.
