### ISSUE TITLE
A script, which finds VA albums, whose filepaths do not contain userdefined strings.

### ISSUE THREAD

**Issue by gitttt54** [Casvt/Plex-scripts#182]
Hello,

this is for music libraries.

I have my VA (Various Artists) albums and normal albums of any artists in different folders, like here:
<img width="721" alt="LIB" src="https://user-images.githubusercontent.com/96403800/211714604-ffdd87f1-8707-4f94-8901-407204bff193.png">

Plex sometimes matches an album from a folder other than a VA-ALBUM-folder as a VA album. 

As a simple example, a soundtrack album (stored inside path "radio-music") from the movie "1999" by prince is matched as a VA album, not as an album by prince as the album artist.
That can cause much trouble within the library, so I'd like to prevent this by manually correcting the album artists of those "wrongly matched" albums. Or better, move those albums into the "VA-ALBUMS" folder.

But the problem is, with many many albums, it is not simple to have an overview and check all the albums by hand.

Therefore I'd like to have a script help me to find all the albums, which are VA but _not_ stored in a VA-ALBUM folder.
(Thats actually the scipt request!)

I need to find albums which are _Various Artists_, defined in plex like this:
<img width="739" alt="VA" src="https://user-images.githubusercontent.com/96403800/211709354-11842ce2-ebdb-49d9-870c-ea6b23b66f14.png">

Those albums (better: the files) must NOT be stored in a path from the library, say "VA-ALBUMS1" and "VA-ALBUMS2". 
If they are stored in any "VA-ALBUMS" paths, then they are just normal VA albums which cause no problems in plex.

But if they are not stored in any "VA-ALBUMS" path, then they must be manually fixed by me.

**Now, what does the script?**

Say, I would run the script like:
`script.py  --library="Musik" --not-in-path="VA-ALBUMS1"  --not-in-path="VA-ALBUMS2" >./output.txt`

The script would scan all music albums in a library named "Musik", one by one.

If an albums has "Various Artists" as Artist Tag,
the script does a string compare like `check if string from path-of-file(s)-in-album contains the given string from --not-in-path=` )

If a match is found (album is in path "VA-ALBUMS1" or "VA-ALBUMS2") then the script skips to the next album.

if NO match is found (album is neither in path "VA-ALBUMS1" nor "VA-ALBUMS2") then the script would simply print out the full path of the album and the album name to the screen (or maybe in a given textfile).

Like here, album + path in a single line:
`Album: "1999 Soundtrack" Path: /mnt/path/to/radio-music/prince/1999 - 1999 Soundtrack/`

Such a list would help me to sort out those albums in question and fix them by hand.

**Now in short:**

A script, which finds VA albums in a defined music library, 
whose filepaths do not contain userdefined strings.

;-D

Is this possible?

Thank you!

**Comment by Casvt** [comment]
Request is too niche to put in the repo but here is a script that would work for you.

```python
from requests import Session
from os.path import dirname

plex_ip = ''
plex_port = ''
plex_api_token = ''

libraries_to_check = ['Musik']
should_be_in_paths = ['/mnt/path/to/VA-ALBUMS1', '/mnt/path/to/VA-ALBUMS2']
artist_name = 'Various Artists'

base_url = f'http://{plex_ip}:{plex_port}'
ssn = Session()
ssn.params.update({'X-Plex-Token': plex_api_token})
ssn.headers.update({'Accept': 'application/json'})

sections = ssn.get(f'{base_url}/library/sections').json()['Directory']
selected_sections = list(filter(
    lambda s: s['type'] == 'artist' and s['title'] in libraries_to_check,
    sections
))

wrong_albums = []
for section in selected_sections:
    lib_output = ssn.get(
        f'{base_url}/library/sections/{section["key"]}/albums'
    ).json()['MediaContainer']['Metadata']

    VA_albums = list(filter(lambda a: a['parentTitle'] == artist_name, lib_output))

    for album in VA_albums:
        album_output = ssn.get(
            f'{base_url}/library/metadata/{album["key"]}/children',
        ).json()['MediaContainer']
        if not album_output['Metadata']: continue

        if not album_output['Metadata'][0]['Media'][0]['Part'][0]['file'].startswith(should_be_in_paths):
            wrong_albums.append(album_output)

# The variable wrong_albums contains the albums. Do with it what you want, below is an example of how you could use it to print info out about each one.
for album in wrong_albums:
    print(f'Album: "{album["parentTitle"]}" Path: {dirname(album_output['Metadata'][0]['Media'][0]['Part'][0]['file'])}')
```

P.S. haven't tested it
