### ISSUE TITLE
Delete media based on tag or collection

### ISSUE THREAD

**Issue by lamepennies** [Casvt/Plex-scripts#194]
With the great reversal from Google storage recently, I was thinking maybe there's a way to selectively remove files from Plex based on a collection or tag. I'm sure this would freeze Plex so maybe you could build in delete 'X' amount before needing to run the script again.

**Comment by Casvt** [comment]
Feature request for: https://github.com/Casvt/Plex-scripts/blob/main/media_management/recent_episode_maintainer.py

**Comment by batch08** [comment]
would also be nice if a script would move contents to a library then we can call that library something like 'Going away (30d)' then deletes it after that number of days
