### ISSUE TITLE
MKV Chapter to Marker

### ISSUE THREAD

**Issue by adamjsturge** [Casvt/Plex-scripts#197]
A lot of mkvs come with chapters already marked with "opening" or "recap". I started making a script to export a JSON from the MKV but was researching how to modify markers when I found your repo. Was wondering if your opening to working on this together. In python there is library called pymkv. I was wondering if this would be a good thing to implement as a part of this or if you could have another way to import a JSON generated by a script

**Comment by Casvt** [comment]
It's not clear to me what exactly you want your script to do, and what you expect from me.
