### ISSUE TITLE
Music video playlist based on playlists already created in plex.

### ISSUE THREAD

**Issue by KINGLIFER** [Casvt/Plex-scripts#204]
In what file should the feature be added? m3u_to_playlist or a new Music video playlists

What is the feature request? Have the m3u_to_playlist have the option to create a music video playlist or collections. As it is no such thing exists whatso ever in the world of plex. Only requirement is the video must have the name and of the song in the playlist (artist name also)

Hope this can be implemented

**Comment by Casvt** [comment]
There is no consistent way to find the music video of a song

**Comment by KINGLIFER** [comment]
not to be rude but did you even try to look?
https://listen.tidal.com/view/pages/mymusic_recommended_videos
(before you say that is just a listing each artist has their videos) example https://listen.tidal.com/artist/10666 (Nelly Furtado)

https://music.youtube.com/new_releases/videos
https://music.youtube.com/search?q=nelly+furtado (Same example under videos... Nelly Furtado)
