### ISSUE TITLE
HTTPS/SSL/TLS support (with self-signed or expired certificates)

### ISSUE THREAD

**Issue by namronb** [Casvt/Plex-scripts#209]
NOTE:  I posted this before I saw the refactor done coincidentally the previous day.  I think the refactor allows HTTPS fine as long as you have an intact certificate trust chain (your cert is not expired and is signed by a CA that is trusted on your local machine).  So this is really about whether anyone needs/wants functionality to use HTTPS with a broken trust chain.  (You know, lazy people like me. :wink: )

---

First, thank you for making this library of scripts available!  I have found it very useful.

I am suggesting a feature that can be used to support https connections for all scripts.  In order to make it work, I had to make the following changes.  Note that (1) and (3) probably aren't necessary if you're using an SSL certificate signed by a known CA.  With my expired certificate, I needed both of these to prevent fatal errors.

1. Import urllib3 (used by requests.Session) and disable warnings globally.
2. Change base_url to use https.
3. All calls to ssn (the requests.Session object) should include the `verify=False` argument.

Below is an example diff based of plex_auto_delete.py.  For brevity, it doesn't offer an option to choose between http and https, which would be important for flexibility.  If you are interested in having your scripts include this feature, I would be willing to start generating pull requests.  Sorry, I generated this diff before your refactor yesterday, but you get the idea.

Thanks!

```
diff --git a/media_management/plex_auto_delete.py b/media_management/plex_auto_delete.py
index 0295ae0..99c812a 100755
--- a/media_management/plex_auto_delete.py
+++ b/media_management/plex_auto_delete.py
@@ -16,12 +16,14 @@ plex_api_token = ''

 from os import getenv
 from typing import List
+import urllib3
+urllib3.disable_warnings()

 # Environmental Variables
 plex_ip = getenv('plex_ip', plex_ip)
 plex_port = getenv('plex_port', plex_port)
 plex_api_token = getenv('plex_api_token', plex_api_token)
-base_url = f"http://{plex_ip}:{plex_port}"
+base_url = f"https://{plex_ip}:{plex_port}"

 value_mapping = {
        'never': '0',
@@ -37,13 +39,13 @@ def plex_auto_delete(ssn, value: str, library_name: str, series_names: List[str]
        if not value_id:
                return 'Invalid value for "value"'

-       sections = ssn.get(f'{base_url}/library/sections').json()['MediaContainer'].get('Directory', [])
+       sections = ssn.get(f'{base_url}/library/sections', verify=False).json()['MediaContainer'].get('Directory', [])
        for lib in sections:
                if lib['title'] != library_name: continue
                if lib['type'] != 'show': return 'Invalid library'

                print(lib['title'])
-               lib_output = ssn.get(f'{base_url}/library/sections/{lib["key"]}/all').json()['MediaContainer'].get('Metadata', [])
+               lib_output = ssn.get(f'{base_url}/library/sections/{lib["key"]}/all', verify=False).json()['MediaContainer'].get('Metadata', [])
                for show in lib_output:
                        if series_names and not show['title'] in series_names:
                                continue
@@ -51,7 +53,8 @@ def plex_auto_delete(ssn, value: str, library_name: str, series_names: List[str]
                        print(f'        {show["title"]}')
                        ssn.put(
                                f'{base_url}/library/metadata/{show["ratingKey"]}/prefs',
-                               params={'autoDeletionItemPolicyWatchedLibrary': value_id}
+                               params={'autoDeletionItemPolicyWatchedLibrary': value_id},
+                               verify=False
                        )
                        result_json.append(show['ratingKey'])
```

**Comment by Casvt** [comment]
In the refactors, you supply the base URL directly. So point 2 is not relevant then.

You say you need to do this because your certificate has expired. Why don't you just fix your certificate?

**Comment by namronb** [comment]
Yeah, I hear you.  I made these changes locally a few months ago and was trying to clean up some to-do items (like posting this), not realizing that you had already enabled https via the URL parameter.  I was assuming that some people might be using self-signed certificates without an intact trust chain (so they would need the other 2 changes), but if that's not the case, it's probably not worth the effort of parameterizing whether or not to allow improper certificates and touching every script.  

One could create a wrapper around `requests.Session` that would store a `verify` member that would be passed through to each `get`/`put` call.  That would mean fewer changes to each file (importing the wrapper library, adding a `--verify` parser argument, and instantiation of the wrapper object instead of a `requests.Session`), but it's still work.  If nobody else is interested in the functionality, I can just close this.  

I'll fix my certificate trust issues and make sure https works for me with the refactor.

**Comment by Casvt** [comment]
Let's do it like this: we close it, but if someone else comes with the same request (a second person) then I'll implement it.
