### ISSUE TITLE
tag_to_collection.py: Error when finding tag

### ISSUE THREAD

**Issue by KennethDenson** [Casvt/Plex-scripts#211]
I'm not 100% sure this is a bug, and not an issue with my system or implementation, so please excuse me if this is a mistake on my part

**In which file is the bug?**   https://github.com/Casvt/Plex-scripts/blob/main/sonarr/tag_to_collection.py

**Describe the setup (arguments and their values, how it was run, etc.)**: I downloaded the script and edited it with the IP, port, token for both Plex and Radarr. I attempted to run it with the following commands:

`python3 tag_to_collection.py -s radarr -t lgbt -l Movies -c LGBTQ+`

**Describe what the bug is**: I'm not sure what should happen next, but I get the following error:

```
Traceback (most recent call last):
  File "/mnt/nas/tag_to_collection.py", line 165, in <module>
    response = tag_to_collection(plex_ssn=ssn, source=args.Source, tag_name=args.TagName, library_name=args.LibraryName, collection_name=args.CollectionName)
  File "/mnt/nas/tag_to_collection.py", line 121, in tag_to_collection
    if tag['label'] == tag_name:
TypeError: byte indices must be integers or slices, not str
```

I thought this might be because I didn't make the script executable so I attempted that but got the same error

**Describe what _should_ be happening**: I'm not sure what I should see in terminal, but the expectation is that this would looks at the movies in Radarr that are tagged lgbt and would update the collection "LGBTQIA+"

Any assistance is appreciated and again, apologies in advance if this is an error on my side.

**Comment by Casvt** [comment]
Seems like radarr changed their api. I'm not sure but I'll check it out.
