### ISSUE TITLE
[Feature Request] restore any markers that are reseted For "intro_marker_editor.py"

### ISSUE THREAD

**Issue by erickyun** [Casvt/Plex-scripts#213]
Hi,

> "Plex will reset any marker adjustments if the item is reanalyzed, which outside of manually reanalyzing a season can also happen if you add a new file to the season." 

To avoid this, I would appreciate it if you could add a feature to the script that manually edits the database, deletes the current markers, and makes Plex re-analyze the local content for markers.

Edit:
As a workaround Could you maybe record all user actions in a separate database or config.json so that we can restore any markers that are reseted?

**Comment by Casvt** [comment]
This can be done using the [plex_exporter_importer.py](https://github.com/Casvt/Plex-scripts/blob/main/server_management/plex_exporter_importer.py) script. Run it with `--Type export --Process intro_marker --All` to export all intro markers of all media into a database file. Then when you want to import them again, run the script with administrator/root privileges and the flags `--Type import --Process intro_marker --Location plex_exporter_importer.db --All`. The script doesn't support credit markers yet, but I'm planning on releasing an improved version of the script soon that adds support for this.
