### ISSUE TITLE
plex_exporter_importer_NEW.py

### ISSUE THREAD

**Issue by hbilbo** [Casvt/Plex-scripts#216]
In which file is the bug?
plex_exporter_importer_NEW.py

Describe the setup (arguments and their values, how it was run, etc.):
python ~/src/plex_exporter_importer_NEW.py -t export -p metadata -l Movies-test -L ~/plex_metadata

Describe what the bug is:
The output file that is exported is an empty .db file with size of 0 bytes. The original plex_exporter_importer.py seems to work. In both scripts however the output .db is placed in the directory where the python file is run, rather than in ~/plex_metadata.

Describe what _should_ be happening:
The plex_exporter_importer_NEW.py should not be outputting an empty file, and they should both be using the "-L" flag correctly.

**Comment by Casvt** [comment]
The NEW file is a work in progress that seems to have accidentally been pushed to GitHub. It's not completed and shouldn't be used.

The "-L" flag might work if you put quotes around the value, like `-L "~/plex_metadata"`. Otherwise provide the full path instead of using `~`.
