### ISSUE TITLE
Audio_Sub_Changer Feature Request

### ISSUE THREAD

**Issue by confuzedplayer** [Casvt/Plex-scripts#217]
Thank you for this amazing script. 
I really like how i am able to set defaults to non-forced subtitles, it's perfect. I've got it running every day on my unraid server with user scripts, but it always scans my whole library. Any chance you could add a way where it only scans new files or ones that have changed (like if I redownload something at a better quality or same file name)? 

Script takes a little time when I run this for my tv shows

**Comment by Casvt** [comment]
> but it always scans my whole library

What do you exactly mean? You process the complete library? The script can also only process specific series/seasons/episodes/movies. See the second example inside the file.

There is no way to know what files are "new" or have "changed" since the last run, so that is for sure not possible.

**Comment by confuzedplayer** [comment]
Oh ok, gotcha. I re-read the second example. i got it. THank you
