### ISSUE TITLE
Plex_exporter_importer:Collections

### ISSUE THREAD

**Issue by RBeatse** [Casvt/Plex-scripts#22]
> Only one feature should be requested per issue. Please make multiple issues if you have multiple feature requests

In what file should the feature be added? Plex_exporter_importer

What is the feature request?
Add support to gather all of the info for collections. Realizing that collections have their own posters, members of the collection (which can cross data directories, libraries, etc) and that members of a collection can be in multiple collections. Knowing if the members of that collection are viewable outside of the collection is also helpful.

**Comment by Casvt** [comment]
Request completed. Please re-download the script to get the new feature. Add `-p collection` to the argument list to export/import/reset all dumb collections (smart collections aren't supported YET).

**Comment by RBeatse** [comment]
Ran into an issue.
[script_output.txt](https://github.com/Casvt/Plex-scripts/files/9062992/script_output.txt)

Here was the command
python3 plex_exporter_importer.py -t export --All -p metadata -p watched_status -p poster -p art -p intro_marker -p collection


Also, you said "Note: The collection is only imported into a library if the library contains every media item that the collection contains. The collection will be imported into multiple libraries if they all contain all media of the collection." 
So, when you do an import (which I haven't done yet), does the import process do all of the regular library things first and THEN do the collections to be sure that they are all updated first?

**Comment by RBeatse** [comment]
And it stopped

[script_output.txt](https://github.com/Casvt/Plex-scripts/files/9063103/script_output.txt)

**Comment by RBeatse** [comment]
I'll have to do that a little later (darn work gets in the way!!).  Is there a little script I could run that would show me what this rogue item and collection is so that I could see what the problem is?

**Comment by Casvt** [comment]
I'll make one quick.

**Comment by RBeatse** [comment]
I finally got around to updating the script and everything ran great!  Thanks.

On the "unmatched", fond them and I have 254!! I tried refreshing metadata and they didn't do anything. Oh well.

**Comment by Casvt** [comment]
Damn that's a lot. Cant help with that sorry. But good to hear that exporting went great 👍
