### ISSUE TITLE
Extra target selectors regarding libraries

### ISSUE THREAD

**Issue by Casvt** [Casvt/Plex-scripts#27]
> Only one feature should be requested per issue. Please make multiple issues if you have multiple feature requests

In what file should the feature be added?
plex_exporter_importer.py

What is the feature request?
Add the arguments '--AllMovies','--AllShows' and, once music is supported, '--AllMusic' to target all [type] libraries. It's an argument set that targets between --All and --LibraryName.

This request was made by @rbeatse

**Comment by RBeatse** [comment]
Thanks. I will try it later today.
