### ISSUE TITLE
Sync poster and collection metadata across libraries

### ISSUE THREAD

**Issue by spicerackk** [Casvt/Plex-scripts#31]
I have a movies library and a kids movie library, and would love to see a way to sync poster and collection details across libraries so collections match, as well as posters across libraries.

**Comment by Casvt** [comment]
Request accepted but I don't have any time currently. Like, zero. I'll make it as soon as I can.

**Comment by Casvt** [comment]
Hey I'm working on the request right now and I have a question for you. I've got poster sync working and I'm now starting on syncing collections. That means that the script will currently support posters and collections. Are there any other things that my script should be able to sync? _Are_ there any more things I can sync that I've forgotten about?

**Comment by Casvt** [comment]
Script request completed. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/various/plex_library_sync.py. It syncs posters and collections. If you have any more feature requests ("It should also sync xyz"), make a feature request for the script. Enjoy!

**Comment by spicerackk** [comment]
So I've downloaded it and am running it after changing the required details for Plex, and it keeps giving me the error:

unrecognized arguments: Movies

My -s SOURCELIBRARYNAME is Movies and the -t TARGETLIBRARYNAME is Kids Movies, as they are in Plex. Am I doing something wrong?

Thanks for actioning this so quickly by the way!

**Comment by Casvt** [comment]
The arguments should look like this: `-s Movies -t "Kids Movies"`

**Comment by spicerackk** [comment]
that worked, thank you!

**Comment by spicerackk** [comment]
Found an issue: if a collection doesn't have a poster assigned, like a custom playlist, it errors out the script, assuming because it can't find a poster to move?

**Comment by Casvt** [comment]
Please make a new bug issue for this. Makes it easier for me to manage the whole project and to keep requests (feature, script, bug) seperate. You can make this bug issue here: https://github.com/Casvt/Plex-scripts/issues/new?assignees=&labels=Bug+request&template=bug-request.md&title=
