### ISSUE TITLE
Remove/clean unused artwork 

### ISSUE THREAD

**Issue by netplexflix** [Casvt/Plex-scripts#37]
With the addition of rating overlays through Plex Meta Manager, a lot of posters are being created. Overtime this inflates the size of Plex's assets considerably.

It would be great to have a script that could clean/remove all unused/unselected artwork (posters mainly, but why not backgrounds as well).

I came across [This script](https://gist.github.com/mblythe86/bad0b1ac5cb76fe94559fe582e683e1a) but that's not easily executable on all platforms. Having a Python version would be great

**Comment by Tharic99** [comment]
May as well add the ability to remove extra files as well. NFO files, txt files, any subtitles, etc. Make it multippurpose and it'll get more utilization.

**Comment by Casvt** [comment]
Good idea both of you

**Comment by netplexflix** [comment]
hi cas! Any idea if this will be possible? I hear a lot of people talking about this, but nobody seems to have figured it out yet

**Comment by Casvt** [comment]
Yeah I think it's possible. I think. It's going to be hard but I think it's possible.

**Comment by Casvt** [comment]
Request completed. The script removes any self-uploaded media that isn't in use. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/various/remove_unused_artwork.py. Enjoy!

**Comment by nicolasrata** [comment]
Awsome, works great thanks a lot !

**Comment by nicolasrata** [comment]
I spoke too quickly, Plex didn't liked it. 
Posters are disappearing. Click on update all metadata doesn't make the posters to reappear. 
any idea ?

![Capture d’écran 2022-06-19 à 15 49 34](https://user-images.githubusercontent.com/20968235/174484371-3389b92e-39b5-4119-84ed-e1f0bea61455.png)

**Comment by Casvt** [comment]
Well the script does the same thing as the script you linked to: https://gist.github.com/mblythe86/bad0b1ac5cb76fe94559fe582e683e1a

So if you're having problems, that script would given them too. I'll look at it again to check if theres something that doesn't match up between that script and my script.

You could fix your media by deleting the library and then creating it again, but then you'll loose all your collections and custom posters and custom Plex metadata. That's a bit destructive so I'll look at less intrusive ways to fix it.

**Comment by nicolasrata** [comment]
I looked into it and I think a way to deal with this is to check if there is multiple poster in Uploads/posters for each bundle.
No - do nothing
Yes - keep the newest and delete the others


Tried to do it by hand and seems to be ok.
