### ISSUE TITLE
Script to delete Movies without subs on Bazarr

### ISSUE THREAD

**Issue by patbowling89** [Casvt/Plex-scripts#38]
Hey Im pretty new at this but Im from Guatemala so my library is mostly dual audio (english and spanish) however before finding good sites to download dual audio content I used radarr/sonarr to download most of my content so I have several movies which bazarr cant find any subtitles in spanish and I would like to get a list of all those from bazarr and delete those movies from my library so I can replace them with a dual audio version however in order to delete them I have to look at my bazarr to know which ones dont have subs and then go to delete the file, if there could be a script that can do that it would be great

**Comment by Casvt** [comment]
So to make it clear: you want a script that goes through bazarr and deleted media files that don't have a certain subtitle?

**Comment by patbowling89** [comment]
Yes correct but only for movies and it needs to make sure that the audio is in english only cause some movies I have only in spanish and because of that they dont have subtitles, so I just need it to delete the movies that are in english and dont have any subtitles files.

**Comment by Casvt** [comment]
Alright thanks
