### ISSUE TITLE
Do not go to next track unless current track is rated in Plex

### ISSUE THREAD

**Issue by Jerrk** [Casvt/Plex-scripts#39]
I would like to set a rating for all of my songs in Plex.

so what i would like is for the player to pause playback if progress is at 99% if the currently playing song is unrated, but i would like for it to keep autoplaying the next song if the current song is rated.

so like a conditional autoplay depending on the rating of the currently playing song.

I use Plexamp windows if that matters

**Comment by Casvt** [comment]
Yeah sure I can make that. Keep in mind the scripts controlling streams only work locally as mentioned in the limitations section of the requesting wiki page.

**Comment by Casvt** [comment]
Too niche. It's been 2 years so you probably don't need it anymore anyway.

**Comment by Jerrk** [comment]
It's still something i would like but if you do not want to do it then i understand 🙂

**Comment by Casvt** [comment]
It's just that nobody is really going to use it except you. It's not worth the time if the result is one user. The scripts need to have a general purpose that all people see use in.
