### ISSUE TITLE
Use a tag from Radarr to maintain a Collection or Genre in Plex

### ISSUE THREAD

**Issue by Adman1020** [Casvt/Plex-scripts#40]
I use this script (https://github.com/Adman1020/Elsewherr) to tag my movies with wether they are available on streaming services. I would like to have this information displayed in Plex in a very obvious way. 

My initial thinking was maybe a custom genre, or a collection. But if there's a better way then that would be great. The aim is that when opening up any movie on any device the user would be able to see that it's available on a streaming service from the information page. This is for when my local movie is broke or poor for any reason and I can go "ah, it's ok, we will watch it on Netflix instead".

Movies can be on multiple streaming services so must be able to have multiple tags/genres/collections. They also move on and off of services (which the Elsewherr script handles) so tags/genres/collections need to be able to be updated. 

It would also be nice to customise the text displayed in Plex as the Elsewherr tags on Radarr are not particularly friendly (i.e. "elsewherr_disney_plus" as a tag on Radarr shows as "Disney+" or something nice in Plex.

**Comment by Casvt** [comment]
So you basically want a script that puts media in a collection if the media is available on the streaming service that that collection is for?

**Comment by Adman1020** [comment]
Yes. Although thinking about it, perhaps something more generic, so a script that puts media into a collection based on the tags against that media within Radarr (and Sonarr). That way this can be done for more than just my use case of streaming services, and instead allows people to use tags in Radarr/Sonarr to populate custom collections in Plex.

**Comment by Casvt** [comment]
Yeah good idea. I'll make it like that!

**Comment by Casvt** [comment]
Request completed. You can find the script here: https://github.com/Casvt/Plex-scripts/blob/main/sonarr/tag_to_collection.py. Enjoy!

**Comment by Adman1020** [comment]
Amazing! Thank you!
