### ISSUE TITLE
Plex Virtual Library (bat script) for TV Shows

### ISSUE THREAD

**Issue by Del-Amitri** [Casvt/Plex-scripts#41]
There’s an old bat script from a few years ago that would make hardlinks of your movie folders if a specific sharing tag was on it in Plex, and put them in a corresponding library folder that you could then point a new Plex library too. Great for syphoning out kid movies. It was called Plex Virtual Library. Worked in SQLite. I’m a total noob to this stuff so it took me a little to get it to work but once I did, it worked flawlessly for movies, I even figure out how to change the syntax for the tag. Problem is, it doesn’t work for shows as tags are applied to the show and not the individual episode/file. I’ve opened up the Plex database with a SQL viewer to try and map out metadata IDs but I can’t get it to work. Would love to see this for shows.

https://github.com/jayrox/PlexVirtualLib

**Comment by Casvt** [comment]
So if I understand it correctly, you want a script that, when a specific sharing tag is added to a media item, creates a hardlink of the media file to a different folder so that it virtually is added to the library attached to the folder and once Plex notices the new "file", it is added to this special library?

**Comment by Casvt** [comment]
Request clarified here: https://www.reddit.com/r/PleX/comments/uu7llh/comment/i9gohj4/?utm_source=share&utm_medium=web2x&context=3

**Comment by Del-Amitri** [comment]
Yup you got it. I used SQLite DB browser to open up the Plex Database to try and follow the metadata, the code is just over my head. I followed up with you on Reddit too (before here) and that gives a more in-depth process of what this actually does when used, including a small caveat when running. Thanks for taking a swing at this, it works great for movies, but would love to have it work for shows as well.

**Comment by Casvt** [comment]
When sharing the library, just restrict it to media that has the desired tag and you have the same result without the extra library. Also, too niche to be included in the repo.

**Comment by Del-Amitri** [comment]
Wow, I'm impressed you got to my request, although I am let down you didn't end up building it.

I respectfully disagree that this is too niche, I see people talk all the time in the Plex forum and Reddit about wanting a sub-library. Some for more crazy drilled down needs, mine is more of a simple layer.

Yes, using tags to restrict media produces a similar result, but that would require manually making multiple libraries then scouring over each one, some with over 5000 entries, to find the titles that apply to that library. Then adding those labels to each user. And repeating that process over and over as new sub-libraries are created. Then being on top of each library as new media is added.

And because libraries can get massive, this would also offload major scan time as it's only scanning the current and potential new files in a library, not every single file that is in the main folder.

My request is extremely helpful for those larger libraries by having an easy way to navigate one primary library with all the media vs multiple manual libraries with all the media. Ideally these sub-libraries would be for large categories with constant released media like kid's movies, not for deceased directors (better suited for Collections).

Example: Main library has every title for every user, which is ideal. I add 'the new Disney movie', which would get a label and be added to "Kids" and "Animation" Libraries, maybe even a Disney library (again, these are both categories with a vast amount of already existing media and a constant flow of new media being released every month/year). I only have to find this movie in my main library and do it once. And if it needs to go elsewhere, I do it then as well.

Keep in mind too, this program exists in SQL as a bat but just for movies. I was hoping someone with more knowledge just clone it for TV Shows.
