### ISSUE TITLE
TBA refresh script

### ISSUE THREAD

**Issue by PierreDurrr** [Casvt/Plex-scripts#42]
With Sonarr, comes a lot of TBA episodes. Would be ideal to search them and refresh metadata only for them

**Comment by Casvt** [comment]
I'm sorry but it's still unclear what should happen with the TBA episodes.

In my script, I find a TBA episode in sonarr. What should I do with it? Trigger the "Refresh & Scan" for the series in sonarr? Go to plex and refresh the plex metadata of the episode? It's just unclear for me what you want to happen with the TBA episodes.

**Comment by PierreDurrr** [comment]
If you could refresh both Sonarr and Plex , that would be awesome ! Or just refresh Plex would be still great

**Comment by Casvt** [comment]
Oh okay now it's clear

**Comment by Casvt** [comment]
Request completed. The script will refresh the sonarr series for every TBA episode. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/sonarr/sonarr_refresh_tba.py. Enjoy!

**Comment by Jerrk** [comment]
When the title in sonarr is refreshed from TBA to the actual title, will it trigger a rename as well or just a refresh?

**Comment by Casvt** [comment]
I don't know if the file is renamed when the episode title changes. You can ask on the sonarr forums if that's the case: https://forums.sonarr.tv/
