### ISSUE TITLE
Connection from IMDb list

### ISSUE THREAD

**Issue by twilsonco** [Casvt/Plex-scripts#45]
Title says it all. User provides a list ID for IMDb, and the script automatically creates a collection for that list using the items in the library that are also on the list. Bonus if it works with TMDb and TVDB as well.

**Comment by twilsonco** [comment]
This is apparently possible with [PlexMetaManager](https://github.com/meisnate12/Plex-Meta-Manager)

I'll be back if it's insufficient :)

**Comment by Casvt** [comment]
I'm making it anyway as other people might want it.

**Comment by Casvt** [comment]
Request completed. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/playlist_collection/list_to_collection.py. Support for tvdb and tmdb lists might come later too.
