### ISSUE TITLE
old FindMedia tool from the Webtools plugin

### ISSUE THREAD

**Issue by Jerrk** [Casvt/Plex-scripts#46]
Just a script that does what the old webtools plugin FindMedia tool did. Which in turn was based on https://github.com/srazer/FindMissing.bundle

Compare a library in Plex with its base folders and find media not imported to Plex. This could be because of corrupt files, incorrect naming, wrong permissions, or just a plex hiccup.

if you feel ambitious you might be able to show the reason why the media was not imported into plex if you read the scanner logs though i'm not sure if that info is made explicitly available.

**Comment by Casvt** [comment]
Interesting request. Definitely will look into this. Finding media that _is_ in the lib folder but not in the library will be easy. Finding the reason is harder but I like a challenge. Searching in the logs might be the solution yeah.

**Comment by Jerrk** [comment]
https://github.com/WebTools-NG/WebTools-NG have added this functionality in 1.0.0 https://github.com/WebTools-NG/WebTools-NG/releases/tag/v1.0.0

so ill close this issue :grin:
