### ISSUE TITLE
Only json files extracting

### ISSUE THREAD

**Issue by RBeatse** [Casvt/Plex-scripts#55]
In which file is the bug?
Plex_export_import.py
Describe the setup (arguments and their values, how it was run, etc.):
running with the new --AllMovie and outputting to a log file
Describe what the bug is:
Only the _metadata.json files are extracting, none of the regular media files extract
Describe what _should_ be happening:
all expected data should be extracted

**Comment by Casvt** [comment]
Don't suspect --AllMovie has to do with this.

Can you run the script the following way:
`python3 path/to/plex_export_import.py -t export --AllMovie`
Note that we don't output to a file and instead just let it output to the terminal.

**Comment by Casvt** [comment]
For the record: resolved in reddit chat. Posters get downloaded at the end and user had never let script run to the end completely once.
