### ISSUE TITLE
Random files using label

### ISSUE THREAD

**Issue by PierreDurrr** [Casvt/Plex-scripts#58]
Currently i'm using a batch script to empty a folder and copy 3 movies that are chosen randomly from my media directory to this folder that is set as library for "Choice of the day".

Basically this could be used in addition to the virtual library script to make it better with no need to copy/delete files every day.
Ability to auto add/remove label, chose number of files to pick, number of days, and bypass files/folders are what come to my mind...

A bit of work here, sorry

**Comment by Casvt** [comment]
In Plex you can just sort your library in a random order. Every time you refresh it's a new order.
