### ISSUE TITLE
plex_loadbalancer.sh not working

### ISSUE THREAD

**Issue by robdplatt** [Casvt/Plex-scripts#6]
I loaded plex_loadbalancer.sh on my backup server for testing, as it runs unRAID. My primary server is Windows.

Here's my config (again, note that in this case "main" is my backup server, and "backup" is my primary server)

> main_plex_ip=192.168.1.69
> main_plex_port=32400
> main_plex_token=***
> 
> main_tautulli_ip=192.168.1.69
> main_tautulli_port=8181
> main_tautulli_token=***
> 
> backup_plex_ip=192.168.1.4
> backup_plex_port=32400
> backup_plex_token=***
> 
> backup_tautulli_ip=192.168.1.4
> backup_tautulli_port=8181
> backup_tautulli_token=***

I already had 2 streams running on Primary (backup for this script) when I started the 5 streams on the Backup (main for this script) server.

![image](https://user-images.githubusercontent.com/13525487/133529914-5ed06f20-d473-4954-ad54-013aa933e4bd.png)

Here's a snip from the Tautulli logs... it does seem like the script is executing. Just not sure what to do about the errors yet. Tautulli and Plex are both run in dockers on my unRAID server.

![image](https://user-images.githubusercontent.com/13525487/133530112-45d3c1f3-89d3-4a7f-a4a7-4a379f982dd1.png)

**Comment by Casvt** [comment]
python-PlexAPI is installed but Tautulli can't use it. Maybe try to install it using the tautulli user like this:
`sudo -u $tautulli_username pip3 install PlexAPI`

**Comment by robdplatt** [comment]
So I ended up running, in total (within the docker)
- apt-get update
- apt-get install jq
- apt-get python3
- apt-get python3-pip
- pip install plexapi

I'm not sure if they were all necessary. I just kept installing things that the logs said were missing until those errors went away. 

I'm left with the following:

![image](https://user-images.githubusercontent.com/13525487/133684028-ef416772-3edd-46f4-aa16-19afa6b0612f.png)


The load balancing isn't working yet. I don't have a /home/tautulli/.cache/pip folder. Still trying to figure that one out.

**Comment by robdplatt** [comment]
Progress. I got rid of the cache error. I accidentally left the other script, plex_failover.sh, enabled. I disabled that script and ran 6 streams on the server. They all ran against the local server.

Here is the only error...

![image](https://user-images.githubusercontent.com/13525487/133685532-1bde106f-d093-4725-9e82-257356514113.png)

Once I get this working, I'll reset the docker image to see what minimum requirements it needs.

**Comment by Casvt** [comment]
Okay thank you. I think I know what's wrong and will let you know when I've updated the script. The requirements for the script are curl, jq, python3, python3-pip and PlexAPI (install using pip3 install PlexAPI).

**Comment by Casvt** [comment]
Hey could you try the debug version that you can now find in the repo? Please share the output.

**Comment by robdplatt** [comment]
Output of starting three streams at once...


> 2021-09-18 19:59:48 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 1 watched.
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_watched'.
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 1.
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: {1} username | is | 'robplatt' > 'robplatt' > True
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Condition logic [blank]: {1} > True
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Custom conditions evaluated to 'True'. Conditions: [True].
> 2021-09-18 19:59:48 - INFO    :: Thread-3 : Tautulli NotificationHandler :: Preparing notification for notifier_id 1.
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Trying to run notify script: /config/scripts/sync_watch_status.py, arguments: ['--ratingKey', '21659', '--userFrom', 'Tautulli=Tautulli', '--userTo', "robplatt=Rob's Server #1 (Primary)"], action: watched
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Full script is: ['/usr/local/bin/python', '/config/scripts/sync_watch_status.py', '--ratingKey', '21659', '--userFrom', 'Tautulli=Tautulli', '--userTo', "robplatt=Rob's Server #1 (Primary)"]
> 2021-09-18 19:59:48 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Executing script in a new thread.
> 2021-09-18 20:00:13 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 1 stopped.
> 2021-09-18 20:00:13 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_stop'.
> 2021-09-18 20:00:13 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:13 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'False'.
> 2021-09-18 20:00:13 - DEBUG   :: Thread-15 : Tautulli ActivityProcessor :: Play duration for session 1 ratingKey 21659 is 35 secs which is less than 120 seconds, so we're not logging it.
> 2021-09-18 20:00:13 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Removing sessionKey 1 ratingKey 21659 from session queue
> 2021-09-18 20:00:19 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 2 started by user 441669 (robplatt) with ratingKey 21659 (***** - Episode 21).
> 2021-09-18 20:00:19 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_play'.
> 2021-09-18 20:00:19 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:19 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
> 2021-09-18 20:00:19 - INFO    :: Thread-3 : Tautulli NotificationHandler :: Preparing notification for notifier_id 2.
> 2021-09-18 20:00:19 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Trying to run notify script: /config/scripts/plex_loadbalancer.sh, arguments: ['yfd6h2xxucp620tryzn28yux'], action: play
> 2021-09-18 20:00:19 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Full script is: ['/config/scripts/plex_loadbalancer.sh', 'yfd6h2xxucp620tryzn28yux']
> 2021-09-18 20:00:19 - DEBUG   :: Thread-3 : Tautulli Notifiers :: Executing script in a new thread.
> 2021-09-18 20:00:19 - DEBUG   :: Thread-30 : Tautulli Notifiers :: Subprocess returned with status code 0.
> 2021-09-18 20:00:19 - INFO    :: Thread-30 : Tautulli Notifiers :: Script notification sent.
> 2021-09-18 20:00:22 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 3 started by user 441669 (robplatt) with ratingKey 21659 (****** - Episode 21).
> 2021-09-18 20:00:22 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_play'.
> 2021-09-18 20:00:22 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:22 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
> 2021-09-18 20:00:22 - INFO    :: Thread-2 : Tautulli NotificationHandler :: Preparing notification for notifier_id 2.
> 2021-09-18 20:00:22 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Trying to run notify script: /config/scripts/plex_loadbalancer.sh, arguments: ['mngrt7jj3nb7ahi9mi4uajf3'], action: play
> 2021-09-18 20:00:22 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['/config/scripts/plex_loadbalancer.sh', 'mngrt7jj3nb7ahi9mi4uajf3']
> 2021-09-18 20:00:22 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
> 2021-09-18 20:00:22 - DEBUG   :: Thread-32 : Tautulli Notifiers :: Subprocess returned with status code 0.
> 2021-09-18 20:00:22 - INFO    :: Thread-32 : Tautulli Notifiers :: Script notification sent.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 2 stopped.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_stop'.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'False'.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-15 : Tautulli ActivityProcessor :: Play duration for session 2 ratingKey 21659 is 7 secs which is less than 120 seconds, so we're not logging it.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Removing sessionKey 2 ratingKey 21659 from session queue
> 2021-09-18 20:00:26 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 2 watched.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_watched'.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 1.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: {1} username | is | 'robplatt' > 'robplatt' > True
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Condition logic [blank]: {1} > True
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Custom conditions evaluated to 'True'. Conditions: [True].
> 2021-09-18 20:00:26 - INFO    :: Thread-2 : Tautulli NotificationHandler :: Preparing notification for notifier_id 1.
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Trying to run notify script: /config/scripts/sync_watch_status.py, arguments: ['--ratingKey', '21659', '--userFrom', 'Tautulli=Tautulli', '--userTo', "robplatt=Rob's Server #1 (Primary)"], action: watched
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['/usr/local/bin/python', '/config/scripts/sync_watch_status.py', '--ratingKey', '21659', '--userFrom', 'Tautulli=Tautulli', '--userTo', "robplatt=Rob's Server #1 (Primary)"]
> 2021-09-18 20:00:26 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 3 stopped.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_stop'.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-3 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'False'.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-15 : Tautulli ActivityProcessor :: Play duration for session 3 ratingKey 21659 is 9 secs which is less than 120 seconds, so we're not logging it.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Removing sessionKey 3 ratingKey 21659 from session queue
> 2021-09-18 20:00:31 - DEBUG   :: Thread-15 : Tautulli ActivityHandler :: Session 3 watched.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_watched'.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking global notification conditions.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 1.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: {1} username | is | 'robplatt' > 'robplatt' > True
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Condition logic [blank]: {1} > True
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli NotificationHandler :: Custom conditions evaluated to 'True'. Conditions: [True].
> 2021-09-18 20:00:31 - INFO    :: Thread-2 : Tautulli NotificationHandler :: Preparing notification for notifier_id 1.
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Trying to run notify script: /config/scripts/sync_watch_status.py, arguments: ['--ratingKey', '21659', '--userFrom', 'Tautulli=Tautulli', '--userTo', "robplatt=Rob's Server #1 (Primary)"], action: watched
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['/usr/local/bin/python', '/config/scripts/sync_watch_status.py', '--ratingKey', '21659', '--userFrom', 'Tautulli=Tautulli', '--userTo', "robplatt=Rob's Server #1 (Primary)"]
> 2021-09-18 20:00:31 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.

**Comment by Casvt** [comment]
Okay thanks. Try the new debug version. After you've done your test with the new version, there will be a new file called "balancer_output" in the same folder as the script. Share that file please.

**Comment by robdplatt** [comment]
> Mon Sep 20 23:25:02 UTC 2021
> Stream started
> Balance: 0 | 0
> Mon Sep 20 23:25:08 UTC 2021
> Stream started
> Balance: 1 | 0
> Moving stream to backup server:
> 	y0ge0anp0bhxiynetdpyap56
> 1
> 2
> 3
> 		No key found
> 	yfd6h2xxucp620tryzn28yux
> 1
> 2
> 3
> 		No key found
>

**Comment by Casvt** [comment]
Okay. It's not switching the streams because it can't find the movie on the other server. I think I know how to fix it. I'll let you know when I've made a new version!

**Comment by robdplatt** [comment]
This particular video is on both servers. However, I did notice the metadata seemed strange as the video date was 1-1-1900 or something, on both servers - even though it's a new episode. I'll give it a try with another piece of media.

What did you have in mind?

**Comment by robdplatt** [comment]
Just tested with a new movie that exists on both servers. I watched it yesterday and the watch status synced to the other server, so I know that it was able to be located. Here is the debug output....

> Wed Sep 22 15:01:31 UTC 2021
> Stream started
> Balance: 0 | 1
> Wed Sep 22 15:01:33 UTC 2021
> Stream started
> Balance: 1 | 1
> Wed Sep 22 15:01:36 UTC 2021
> Stream started
> Balance: 2 | 1
> Moving stream to backup server:
> 	kjlnilf8gh6o6pof2m7d429u
> 1
> 2
> 3
> 4
> 5
> 6
> Stopping current stream from main server
> Couldnt stop the stream
> 	3x7fe5az25imz5an92xcdiz9
> 1
> 2
> 3
> 4
> 5
> 6
> Stopping current stream from main server
> Couldnt stop the stream
> 	uru7t5d3bzrjxwbm6b3pir1w
> 1
> 2
> 3
> 4
> 5
> 6
> Stopping current stream from main server
> Couldnt stop the stream


Here's an error from the Tautulli Log

> 2021-09-22 15:01:36 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Trying to run notify script: /config/scripts/plex_loadbalancer.sh, arguments: ['kjlnilf8gh6o6pof2m7d429u'], action: play
> 2021-09-22 15:01:36 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Full script is: ['/config/scripts/plex_loadbalancer.sh', 'kjlnilf8gh6o6pof2m7d429u']
> 2021-09-22 15:01:36 - DEBUG   :: Thread-2 : Tautulli Notifiers :: Executing script in a new thread.
> 2021-09-22 15:01:40 - DEBUG   :: Thread-28 : Tautulli Notifiers :: Subprocess returned with status code 0.
> 2021-09-22 15:01:40 - ERROR   :: Thread-28 : Tautulli Notifiers :: Script error: 
>   Traceback (most recent call last):
>     File "<stdin>", line 6, in <module>
>     File "/app/lib/plexapi/server.py", line 416, in client
>       raise NotFound('Unknown client name: %s' % name)
>   plexapi.exceptions.NotFound: Unknown client name: Chrome
>   Traceback (most recent call last):
>     File "<stdin>", line 6, in <module>
>     File "/app/lib/plexapi/server.py", line 416, in client
>       raise NotFound('Unknown client name: %s' % name)
>   plexapi.exceptions.NotFound: Unknown client name: Chrome
>   Traceback (most recent call last):
>     File "<stdin>", line 6, in <module>
>     File "/app/lib/plexapi/server.py", line 416, in client
>       raise NotFound('Unknown client name: %s' % name)
>   plexapi.exceptions.NotFound: Unknown client name: Chrome
> 2021-09-22 15:01:40 - INFO    :: Thread-28 : Tautulli Notifiers :: Script notification sent.
> 2021-09-22 15:01:41 - DEBUG   :: Thread-4 : Tautulli ActivityHandler :: Session 1 has changed transcode decision.
> 2021-09-22 15:01:44 - DEBUG   :: Thread-4 : Tautulli ActivityHandler :: Session 2 has changed transcode decision.
> 2021-09-22 15:01:46 - DEBUG   :: Thread-4 : Tautulli ActivityHandler :: Session 3 has changed transcode decision.

**Comment by Casvt** [comment]
Okay thanks. The info that you're giving is very helpful. I'm going to look at it and investigate what it is. 

> It's not switching the streams because it can't find the movie on the other server.

> What did you have in mind?

Currently, the script notes the "guid" of the movie on the main server. Then it searches for the title on the backup server and checks if one of the results matches that guid. If it does, it will switch to that movie.

The problem is that if you have the movie metadata on the main server sourced from the movie database (tmdb) and the Internet Movie Database (imdb) on the backup server for example, it will not match so it can't find the movie even though it's there. Purely because on the main server the guid reports the tmdb id and on the backup server it reports the imdb id.

**Comment by robdplatt** [comment]
All of my settings between my two servers are the same. I have a watch status sync script that works 99% of the time. I just happened to have a string of episodes in a show that aren't getting the right metadata. My hunch is it's related to the new Plex TV agent that was just updated.

This last test was a movie that synced fine and has the same metadata. Though if you have anything you want me to peek at from the XML to be sure. Just checked the guid and it's the same.

**Comment by Casvt** [comment]
Okay can you try the new version? I have tested the script in my own testing environments and there it worked so I concluded that it had to do with something specific for you. I noticed that all three clients that you used had the name "Chrome", which is totally normal (three times a web client). The thing is that I select the client to control by it's name, which gave errors as multiple clients returned for the name.

So what I added was a variable that contains the machine_id (unique for every client) and supply that (on top of the name) to Python-PlexAPI so that it will always control the correct client and only that client. This is more of a general bug that you encountered than a problem with your setup. I have to admit that I don't know what to do if it doesn't work now but we'll see when it comes to that point.

I haven't fixed the following yet, but that isn't of importance now and not critical to the workings of the script so it doesn't matter right now.

> The problem is that if you have the movie metadata on the main server sourced from the movie database (tmdb) and the Internet Movie Database (imdb) on the backup server for example, it will not match so it can't find the movie even though it's there. Purely because on the main server the guid reports the tmdb id and on the backup server it reports the imdb id.

**Comment by robdplatt** [comment]
Interesting. Is there any way to capture the chrome session ID? I was testing with multiple tabs from the same client, unaware that this script would only work with unique clients. That said I can still test this out.

**Comment by robdplatt** [comment]
OK I started two streams remotely, then started 1 stream, locally, and it didn't move. This media is on both servers with the same guid.


> Thu Sep 23 14:52:18 UTC 2021
> Stream stopped
> Balance: 0 | 0
> Thu Sep 23 14:52:31 UTC 2021
> Stream started
> Balance: 0 | 0
> Thu Sep 23 14:52:56 UTC 2021
> Stream started
> Balance: 1 | 0
> Moving stream to backup server:
> 	fzuuk95nxrgw4sph3uzno8wq
> 		No key found
> 	gjxdiz6lhnf8y84cf1hjmazu
> 		Not local
> Thu Sep 23 14:53:35 UTC 2021
> Stream stopped
> Balance: 1 | 0
> Thu Sep 23 14:53:51 UTC 2021
> Stream started
> Balance: 1 | 0
> Moving stream to backup server:
> 	tzwx0zscog8yvjd5ak0upb9b
> 		Not local
> 	gjxdiz6lhnf8y84cf1hjmazu
> 		Not local
> Thu Sep 23 14:54:13 UTC 2021
> Stream started
> Balance: 2 | 0
> Moving stream to backup server:
> 	fzuuk95nxrgw4sph3uzno8wq
> 		No key found
> 	gjxdiz6lhnf8y84cf1hjmazu
> 		Not local
> 	tzwx0zscog8yvjd5ak0upb9b
> 		Not local

**Comment by Casvt** [comment]
Okay please run the new version. First of all I changed the logging to be more informative and easier to read/understand. Second of all I changed some things in the URL used for searching the movie on the other server. I wasn't replacing spaces with %20 (url encoding) so if the movie name had more than one word, the search would fail, it can't find the key of the movie and so it can't switch that stream. In my testing I was using the movie "Tenet" which is only one word so I wasn't encountering that problem.

This is probably the reason for not being able to find the key (what is being reported twice in the logs that you shared).

> Interesting. Is there any way to capture the chrome session ID?
You misunderstand. The machine_id is the unique id given to a PLEX client (the chrome session ID has nothing to do with this). So if you have three google tabs open with three streams, you still have three machine_ids; one for every client. You can totally run three streams in one chrome session. I use the unique id's so that I can specifically control "the third one" or "the first one" in the chrome session.

**Comment by robdplatt** [comment]
Update. Two streams on "second server", no streams on "primary server". I started 6 streams of the same show on the "primary server". No Key found.

> 23/09/2021 20:28:27 | Stream started
> 23/09/2021 20:28:28 | Balance: 1 | 2
> 23/09/2021 20:28:31 | Stream started
> 23/09/2021 20:28:31 | Balance: 3 | 2
> 23/09/2021 20:28:32 | Stream started
> 23/09/2021 20:28:32 | Balance: 3 | 2
> 23/09/2021 20:29:22 | Stream started
> 23/09/2021 20:29:22 | Balance: 4 | 2
> 23/09/2021 20:29:22 | Moving stream to backup server:
> 23/09/2021 20:29:22 | 	nvfvvn4t61w7b0ahaf1ko276
> 23/09/2021 20:29:22 | 		No key found
> 23/09/2021 20:29:22 | 	4pu9dfbbhxfge65nqm0i8gyf
> 23/09/2021 20:29:22 | 		No key found
> 23/09/2021 20:29:22 | 	4ewpxvpk3wh0ojgr6s4poxjc
> 23/09/2021 20:29:23 | 		No key found
> 23/09/2021 20:29:23 | 	bbq3eopq7rocobcix30z7u6d
> 23/09/2021 20:29:23 | Stream started
> 23/09/2021 20:29:23 | Balance: 5 | 2
> 23/09/2021 20:29:23 | Moving stream to backup server:
> 23/09/2021 20:29:23 | 		No key found
> 23/09/2021 20:29:23 | 	wz0dj51kvagbb5ia097g75jm
> 23/09/2021 20:29:23 | 		No key found
> 23/09/2021 20:29:23 | 	4pu9dfbbhxfge65nqm0i8gyf
> 23/09/2021 20:29:23 | 		No key found
> 23/09/2021 20:29:23 | 	4ewpxvpk3wh0ojgr6s4poxjc
> 23/09/2021 20:29:24 | 		No key found
> 23/09/2021 20:29:24 | 	bbq3eopq7rocobcix30z7u6d
> 23/09/2021 20:29:24 | 		No key found
> 23/09/2021 20:29:24 | 	nvfvvn4t61w7b0ahaf1ko276
> 23/09/2021 20:29:24 | 		No key found
> 23/09/2021 20:29:29 | Stream stopped
> 23/09/2021 20:29:29 | Balance: 4 | 2
> 23/09/2021 20:29:31 | Stream started
> 23/09/2021 20:29:32 | Balance: 5 | 2
> 23/09/2021 20:29:32 | Moving stream to backup server:
> 23/09/2021 20:29:32 | 	nvfvvn4t61w7b0ahaf1ko276
> 23/09/2021 20:29:32 | 		No key found
> 23/09/2021 20:29:32 | 	4pu9dfbbhxfge65nqm0i8gyf
> 23/09/2021 20:29:32 | 		No key found
> 23/09/2021 20:29:32 | 	4ewpxvpk3wh0ojgr6s4poxjc
> 23/09/2021 20:29:32 | 		No key found
> 23/09/2021 20:29:32 | 	bbq3eopq7rocobcix30z7u6d
> 23/09/2021 20:29:33 | 		No key found
> 23/09/2021 20:29:33 | 	wz0dj51kvagbb5ia097g75jm
> 23/09/2021 20:29:33 | 		No key found
>

**Comment by robdplatt** [comment]
I stopped all of my streams and switched to a one word movie. I started 5 streams.

> 
> 23/09/2021 20:30:59 | Stream stopped
> 23/09/2021 20:30:59 | Balance: 5 | 2
> 23/09/2021 20:31:01 | Stream stopped
> 23/09/2021 20:31:01 | Balance: 4 | 2
> 23/09/2021 20:31:04 | Stream stopped
> 23/09/2021 20:31:04 | Balance: 3 | 2
> 23/09/2021 20:31:06 | Stream stopped
> 23/09/2021 20:31:06 | Balance: 2 | 2
> 23/09/2021 20:31:08 | Stream stopped
> 23/09/2021 20:31:08 | Balance: 1 | 2
> 23/09/2021 20:31:08 | Moving stream to main server:
> 23/09/2021 20:31:08 | 	egwhrhez9so14jf1v8yzs5yw
> 23/09/2021 20:31:08 | 		Not local
> 23/09/2021 20:31:08 | 	c9n9jn938l9iu0fflkr9vfcu
> 23/09/2021 20:31:09 | 		No key found
> 23/09/2021 20:31:11 | Stream stopped
> 23/09/2021 20:31:11 | Balance: 0 | 2
> 23/09/2021 20:31:11 | Moving stream to main server:
> 23/09/2021 20:31:12 | 	egwhrhez9so14jf1v8yzs5yw
> 23/09/2021 20:31:12 | 		Not local
> 23/09/2021 20:31:12 | 	c9n9jn938l9iu0fflkr9vfcu
> 23/09/2021 20:31:12 | 		No key found
> 23/09/2021 20:31:36 | Stream started
> 23/09/2021 20:31:36 | Balance: 2 | 2
> 23/09/2021 20:31:36 | Stream started
> 23/09/2021 20:31:36 | Balance: 2 | 2
> 23/09/2021 20:31:36 | Stream started
> 23/09/2021 20:31:36 | Balance: 3 | 2
> 23/09/2021 20:31:38 | Stream started
> 23/09/2021 20:31:38 | Balance: 4 | 2
> 23/09/2021 20:31:38 | Moving stream to backup server:
> 23/09/2021 20:31:38 | 	vw0rgpanw75m7d53192mt3h6
> 23/09/2021 20:31:39 | 		Stopping current stream from main server
> 23/09/2021 20:31:41 | 		Couldnt stop the stream
> 23/09/2021 20:31:41 | 	hi5asmmfd99n89cuk6897pey
> 23/09/2021 20:31:42 | 		Stopping current stream from main server
> 23/09/2021 20:31:43 | 		Couldnt stop the stream
> 23/09/2021 20:31:43 | 	d24l9ukvab9czggl765wvrl9
> 23/09/2021 20:31:43 | 		Stopping current stream from main server
> 23/09/2021 20:31:44 | 		Couldnt stop the stream
> 23/09/2021 20:31:44 | 	r2qh43mrg3svy33ffj6zbk5r
> 23/09/2021 20:31:45 | 		Stopping current stream from main server
> 23/09/2021 20:31:45 | 		Couldnt stop the stream
