### ISSUE TITLE
Argument --AllShows not working with -P arg

### ISSUE THREAD

**Issue by RBeatse** [Casvt/Plex-scripts#63]
In which file is the bug?
Plex_exporter_importer
Describe the setup (arguments and their values, how it was run, etc.):
python3 plex_exporter_importer.py -t export --AllShows -P 
Describe what the bug is:
The terminal window flew past (1,000 TV Shows in about 15 seconds) with all of the show names and libraries but nothing actually updated (no media, no jsons)
Describe what _should_ be happening:
All posters, etc., and the metadata should be exported (but no episode posters)

**Comment by Casvt** [comment]
I'm able to reproduce.

**Comment by Casvt** [comment]
Found the problem. Give me one second to fix and upload

**Comment by Casvt** [comment]
Bug fixed. Please re-download to get the new version.
