### ISSUE TITLE
Possible for auto_audiochannels.py to be more selective?

### ISSUE THREAD

**Issue by Christian-Martinez1** [Casvt/Plex-scripts#7]
Hey mate, thank you so much for this collection of scripts, they are VERY useful. Particularly the auto_audiochannels script. 

My issue is I have 2160p Remuxes and due to Plex not being able to Direct Play TrueHD 7.1 audio (particularly on Apple TVs) if it is the default audio track then Plex will transcode and not direct play my movies. So I am using this to change the default audio within the movies to a 6 channel track rather than the 8 channel true HD. I have two questions that you can hopefully assist with:

First of all for this to be useful it would need to change the audio for everyone I am sharing my Plex server with; As I do not want my family to be transcoding 4k content, will this script change the default audio track for everyone with access to my plex server (since I am providing the API token) or is it just for me?

Second, if the above is true and it changes the default audio for everyone, is it possible for me to modify the script to be a bit more selective? For example, DTS-HD MA 7.1 audio will direct play to Apple TV without transcoding even though it is an 8 channel audio like TrueHD which will not direct play; Can I modify the script to select audio formats if they are available? Like if an audio track exists containing 8 channels and DTS in the name then select that as default (DTS-HD MA 7.1), else if track exists containing 6 channels and contains DTS in the name select that (DTS-HD MA 5.1),, else if track exists containing 6 channels and has AC3 5.1 in the name select that (EAC3 5.1), etc?

I'm really hoping this script can affect all users else I'll have to just set up a separate 4k library/replace my 4k content with 1080p Remuxes as they don't contain TrueHD for the most part.

Thanks again for all your work and I look forward to a reply!

**Comment by Casvt** [comment]
Hey,

The selection of the audio track is user specific. That means that the script only affects you. It doesn't change it for other users. However, I can make a v2 in which I support user selection.
So '--User user1 --User user2' to apply the script to the users that have access to your server who have the username user1 or user2. Or '--User @all' to target everyone.

The second point is a bit harder. I would first need to look if I can see the audio format in Plex. Then I would need to incorporate somesort of if-elif-else-except system for choosing an audio stream.
And if I understand your example correctly, the script would basically be: 'Select the audio track with the highest channel count that doesn't need transcoding.' Is this correct?

I'm very busy right now but I'll look when I can update the script. I'll update the script in general to make it a bit better optimized and such.

**Comment by Christian-Martinez1** [comment]
Spot on on both first and second points, that would be sick if it can be done. I basically would have to either remux everything right after download to remove the audio track if it can’t as the server I rent is not powerful enough to transcode down 4k remuxes and I want to direct play wverything only. 

Super stupid how Plex doesnt have an option to force/require direct play only but thats another issue I guess lol. 

Well thanks so much for your help mate, just let me know if you will eventualy add these options or not so that I can download 1080p content instead if need be. 

Happy holidays and thanks again!

**Comment by Casvt** [comment]
> Super stupid how Plex doesnt have an option to force/require direct play only but thats another issue I guess lol.

If you have Plex pass, I can make a script that kills any transcode session. It wouldn't allow you to start a transcode stream. But if you have media that can only be watched via transcoding, you would literally not be able to watch the media.

Just saying some thoughts out loud. If you come up with a plan/an idea, I'll make it for you. Don't consider 'but I don't think that's possible'. Say anything.

**Comment by Christian-Martinez1** [comment]
> > Super stupid how Plex doesnt have an option to force/require direct play only but thats another issue I guess lol.
> 
> If you have Plex pass, I can make a script that kills any transcode session. It wouldn't allow you to start a transcode stream. But if you have media that can only be watched via transcoding, you would literally not be able to watch the media.
> 
> Just saying some thoughts out loud. If you come up with a plan/an idea, I'll make it for you. Don't consider 'but I don't think that's possible'. Say anything.

That is the least of my worries at the current moment as I think I'd rather get the media streamable by just pressing play. Most of the fam isn't technically saavy, particular parents and their siblings and to get 2160p remuxes to stream from the beginning, they need to click the "..." next to the Play button, then go to playback settings, then change the track, and thats already like 3 clicks too many lol. I'd love to get it set up with clicking play and it just works. They all have decent internet, at least 200Mbps so direct playing even 4k remuxes won't be an issue, I just got to make it work for now. 

I see another set of programs that can possibly be used, mkvtoolnix. Howeder I would have to use mkvinfo to see the properties of the files after they are downloaded as a post-processing script then mkvpropedit to set the default track flag within the mkv file itself; Not sure if you can even see full audio track names this way, I haven't tested this out yet but am going to start today. 

Honestly no idea why this isn't an even bigger issue, because apparently even the Shield Pro cannot direct play TrueHD audio so a lot of people have to be having some sort of related issue to this I would think.

**Comment by Christian-Martinez1** [comment]
Update: You can forget about this if its not something anyone else has expressed interest in; As my library isn't super huge yet I opted to purge and redownload my entire 4k library and use mkvmerge to output the media file's properties to a json format and then parsed it into a PSCustomObject. From then, I used mkvpropedit to check audio track headers for TrueHD and disable the audio if it exists and set a different track to default according to priority from DTS 7.1 down to AAC 2.0. 

I did this all in powershell core as I am not very familiar with python or shell script as much. I am testing it now as a post-processing script for sabnzbd but if you are interested I can post it here; It could be modified to iterate through an existing plex library but it doesn't work well with rclone mounted remotes as you have to stream over the entire file to modify the props which is kinda crappy for 60Gb remuxes.
