### ISSUE TITLE
Alternate Order Playlist not working for a show

### ISSUE THREAD

**Issue by HStep20** [Casvt/Plex-scripts#71]
In which file is the bug?

alternate_ordering_playlist.py 

Describe the setup (arguments and their values, how it was run, etc.):

Tried to run it for an anime show, to get a playlist with the chronological order built, but I think because of the way its mapped to one season, where the normal show is mapped across two seasons, it may be causing some issues. The command to run it is:

/usr/bin/python3 /scripts/plex/create_plex_playlist_for_alternate_tvdb_ordering.py -s "The Melancholy of Haruhi Suzumiya" -o "2009 Series" --NoWatched

I use the exact command with the -s -o args changed for other shows, and it works great on those. Just this one seems to be causing some issues.

Describe what the bug is:

Creates an empty playlist, instead of one following the alternate order of '2009 series'. The show is completely unplayed

**Comment by Casvt** [comment]
I've found the place where the bug is. At line 72 inside the script, tvdb_ids should contain the tvdb ids of all the episodes, but with this series, the list is empty. That's why your playlist is empty. I'm now going to take a look at why it's empty and how to fix it.

**Comment by Casvt** [comment]
Bug fixed. Please redownload the script to have the patched version.

**Comment by Casvt** [comment]
Well I don't know then. I thought I fixed it (and worked for me) but it still doesn't for you? Weird. Your proposal to pull it into a debugger is a good plan. You sound like you know what you're doing concerning programming and scripts so I'll ask it in more technical terms. When pulling the script into the debugger and you run it (on _only_ the anime series), please share the values of the following variables:

1. show_guid, on line 46
2. seasons, on line 49
3. orders, on line 50
4. links, on line 51
5. link, on line 65
6. tvdb_ids, on line 72
7. id_map, after line 90

Those would be all the values I'd need to exactly know what's going on (and thus find out where it's going wrong). You can share the values in the form of a file or just paste them here; it's all fine with me as long as I can get the values.

**Comment by HStep20** [comment]
show_guid = 79414

seasons = ''<h2>Seasons</h2>\r\n                    <ul class="nav nav-pills seasontype">\r\n                                    <li role="presentation" class=" active "><a href="#tab-official" class="change_seasontype" data-type="1" data-toggle="pill">Aired Order</a></li>\r\n                                    <li role="presentation" class=""><a href="#tab-dvd" class="change_seasontype" data-type="2" data-toggle="pill">DVD Order</a></li>\r\n                                    <li role="presentation" class=""><a href="#tab-absolute" class="change_seasontype" data-type="3" data-toggle="pill">Absolute Order</a></li>\r\n                                    <li role="presentation" class=""><a href="#tab-alternate" class="change_seasontype" data-type="4" data-toggle="pill">2009 Series</a></li>\r\n                            </ul'"

orders = ['Aired Order', 'DVD Order', 'Absolute Order', '2009 Series']

links = ['/series/the-melancholy-of-haruhi-suzumiya/allseasons/official', '/series/the-melancholy-of-haruhi-suzumiya/allseasons/dvd', 'https://thetvdb.com/series/the-melancholy-of-haruhi-suzumiya/seasons/absolute/1', 'https://thetvdb.com/series/the-melancholy-of-haruhi-suzumiya/seasons/alternate/1']

link = 'https://thetvdb.com/series/the-melancholy-of-haruhi-suzumiya/seasons/alternate/1'

tvdb_ids = ['7795224', '7795306', '7795307', '7795308', '7795309', '7795310', '7795311', '7795312', '7795313', '7795314', '7795315', '7795316', '7795317', '7795319', ...]  (Length is 28)

id_map = {'2046571': '138179', '307995': '138149', '307996': '138150', '307998': '138151', '307999': '138152', '308000': '138153', '308001': '138154', '308002': '138155', '308003': '138156', '308004': '138157', '308005': '138158', '308006': '138159', '308007': '138160', '308008': '138161', ...} (This one has a length of 29, for some reason)

Where it seems to fail is in line 93. It never actually passes the if statement there, so as a result, nothing gets appended to the result_json. When it finishes running, the result_json is just an empty list.

**Comment by Casvt** [comment]
Everthing is alright until we start doing stuff with the id_map and matching the tvdb_ids with the id_map. Just what I'm thinking right now

**Comment by HStep20** [comment]
Im not quite sure what the rating key is, since I havent played with plex through the api, but why use that instead of the episode['GUID'] tvdb id value? It seems easier to match directly to that, instead of using a map

**Comment by Casvt** [comment]
We get the list of episodes (in the special order) from tvdb. This list contains the tvdb ids of the episodes, in the special order. That is stored in the tvdb_ids list. (line 70-72)

However, to make a playlist in plex, we need to give a list of ratingkeys (the name plex gives for "unique id for every media item" principle). So we need to "convert" the tvdb ids to plex ratingkeys. We use id_map for that. The keys in id_map are the tvdb id's of all the plex episodes and the values are the corresponding ratingkeys. (line 74-89)

Now we're going to iterate over the tvdb ids (tvdb_ids) and one by one get the corresponding ratingkey by querying the id_map. We add the resulting ratingkey to a new list and this way loop through every episode mentioned in the tvdb result. At the end of this, we have a list (result_json) which contains the ratingkeys of all the episodes in the order of the tvdb result (which is in it self in the order that you gave). (line 91-94)

I'm still not sure what's going wrong but I'm thinking it has something to do with the fact that the ids in tvdb_ids and the keys in id_map don't even come close, even though they should match up.

**Comment by HStep20** [comment]
Huh, weirdly enough, if you go to TVDB, and look at the episodes under both orderings, they actually have different ID's for some reason. 

https://thetvdb.com/series/the-melancholy-of-haruhi-suzumiya/episodes/307996

https://thetvdb.com/series/the-melancholy-of-haruhi-suzumiya/episodes/7795224

Same names, but different actual episode IDs, Airdates, and metadata in general. This is the root of the issue, and unless you match by episode names instead of ID to build alternate orders for odd edge cases like this, I don't know that it's possible in the way the script runs now. Even weirder, the Aired Order/DVD Order both share episode metadata, and the 2009 Series order/Absolute Order share metadata. It almost seems like 2 shows smooshed together into one entry on tvdb

**Comment by Casvt** [comment]
Yeah I think that's the problem. There is no problem with the script. There's a problem with the tvdb. Theres not much I can do about this sorry. But thanks for helping with finding out what's wrong.
