### ISSUE TITLE
Plex Users Default to Remote Stream 1080p (8mbps)

### ISSUE THREAD

**Issue by Koyakami** [Casvt/Plex-scripts#76]
Plex for some unknown reason (has been complained about for many years from what I've seen) defaults "remote stream" to 720p, so all users need to go into their settings and amend their remote stream to a higher res/original manually.

I wondered if a script could be made to default make users remote stream be set to 8mbps.  I mention this specifically due to my upload plus amount of users I have, 8mbps is best for me.

Much appreciated dude! No rush though.

**Comment by Casvt** [comment]
I can just make a script that goes to every users settings, and sets the remote streaming option to 8mbps. That simple. Agree?

**Comment by Koyakami** [comment]
Yeah that will do the trick pal.

**Comment by edrock200** [comment]
> I can just make a script that goes to every users settings, and sets the remote streaming option to 8mbps. That simple. Agree?

How would this change the setting on the remote client since it's not an account setting?

**Comment by Casvt** [comment]
> How would this change the setting on the remote client since it's not an account setting?

It _is_ an account setting. When you go into settings, you'll see that the setting is under "Quality" -> "Video quality" and not under one of the settings of the server which means that it's for the account and not the server.

**Comment by Casvt** [comment]
> Interesting. My clients don't share that setting across, but that setting will persist across browsers, but maybe that's changed now. I'll have to check it out.

Well it's all very weird. I mean it really isn't clear to me if this setting applies to the selected server or for all servers or for only this client. It's very vague to me. And I haven't even managed yet to edit the setting using a script because plex's api is complete shit.

I've been able to edit server settings with a script but not user settings. You get it: just changing the value of one setting turns out to be quite complicated.

**Comment by Casvt** [comment]
Hey I've been doing some more research and I'm basically coming to the conclusion that it's impossible to do this. The clients have to do it themselves; I can't change a setting on the client via the api.

I'm sorry but there's nothing I can do.
