### ISSUE TITLE
Put overseer requests into a collection

### ISSUE THREAD

**Issue by 8bit-echo** [Casvt/Plex-scripts#78]
When a movie is requested with Overseer, it would be great to have all requested movies in a “Requested” collection together.

**Comment by Casvt** [comment]
So just a script that puts all requested movies in a collection? That's easy

**Comment by Casvt** [comment]
Request completed. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/various/overseerr_to_collection.py. Enjoy!

**Comment by 8bit-echo** [comment]
you're awesome. Thanks
