### ISSUE TITLE
Qbittorrent Script: Change/Set category based on tag

### ISSUE THREAD

**Issue by CptChaz** [Casvt/Plex-scripts#82]
I have a third party program that tags certain torrents. What i'd like the script to do, is change/set the category of any torrents with that specific tag. So something like:

if [ tag = xyz ];

then

   [ change category to ABC ]

I assume this would use qbit's mechanism of "Run external program on torrent completion" but if there's another/better way, i'm all ears for that, too. Thanks in advance!

**Comment by CptChaz** [comment]
as an aside, would it be possible to add a timer into this script? so if it's triggered "on torrent completetion", then "x" minutes later it will change the categories? 

(my 3rd party program runs once an hour to apply tags, so new torrents may have some delay)

**Comment by Casvt** [comment]
You're requesting a script that "finds torrents with cat A and sets it to cat B". And the cat A is applied by a software. Why not make the software immediately set the torrent to cat B?

Software -> Cat A -> script -> Cat B
Software -> Cat B

**Comment by CptChaz** [comment]
Not quite. torrents with **TAG** "A" need to be set to a specific _category_. The third party software has no ability to set categories unfortunately - it only sets a tag. so i'm looking for something more like this:

Software -> **Tag** A -> script -> Cat B

**Comment by Casvt** [comment]
Oh okay now I understand haha. This makes a lot more sense. Yeah I can totally do this.

**Comment by CptChaz** [comment]
Awesome. You have my most sincere gratitude, thank you.

**Comment by Casvt** [comment]
Request completed. You can find it here: https://github.com/Casvt/Plex-scripts/blob/main/various/qbittorrent_tag_to_cat.py. You wanted a timer so you add -w [seconds] to the argument list. Enjoy!
