### ISSUE TITLE
Email Script: Allow custom subject and message

### ISSUE THREAD

**Issue by nobodyspecial** [Casvt/Plex-scripts#83]
I'd like a script to send email notifications and allow me customize the subject and message for Sonarr, Radarr, and Lidarr. Ideally I'd like to be able to put show names in the subject field instead of "Sonarr - Episode Downloaded" which is sent with the default email notification. Thanks!

**Comment by Casvt** [comment]
Request denied with explanation here: https://www.reddit.com/r/PleX/comments/uu7llh/edition_2_of_ill_make_any_script_suggestions_you/ia7i3eg?utm_medium=android_app&utm_source=share&context=3
