### ISSUE TITLE
How does audio_sub_changer.py handle forced / non-forced subtitles?

### ISSUE THREAD

**Issue by Mushin** [Casvt/Plex-scripts#84]
Please could you clarify how this script handles forced / non-forced subtitles?

My use case is that I'd like to auto select English subtitles, where available, rather than English Forced (which are often auto selected by Plex).

**Comment by Casvt** [comment]
I realise that it just selects the first audio/subtitle stream with the target language regardless of being a "special version" or not. It should have a certain order which specifies which version to prefer if multiple exist.

You can make a feature request for the script asking for more control over the selection of the track, looking at the "version" of the stream.
