### ISSUE TITLE
Show, if actors/actresses are gone...

### ISSUE THREAD

**Issue by gitttt54** [Casvt/Plex-scripts#86]
I have a crispy one...

On a Movie page, Plex shows actor images. 
Lets say, I want to see, if an actor/actress is deceased, 
it would be nice, if the image was b/w instead or coloured, or in a single* color or has a watermarked [red cross](https://image.emojipng.com/401/1769401.jpg) or something [else](https://www.emojipng.com/preview/1136063) to show the [actor](https://www.emojipng.com/preview/3391298)/[actress](https://www.emojipng.com/preview/3391317) is deceased.
Wikipedia will help finding, if someone is deceased, via "the [Died](https://en.wikipedia.org/wiki/Bob_Hoskins) Info" (Not sure, if they offer an API). Or, of course, [themoviedb](https://www.themoviedb.org/person/382-bob-hoskins) or [thetvdb](https://thetvdb.com/people/353820-bob-hoskins) have infos too.

The Script would go over all actors/actresses from Plex, 
and gather the "died" information from any Database mentioned above,
If there is a gathered "died-date" and the "died-date" is in the past (from the date the script is running),
then some actions are taken to manipulate/change the image.
(maybe, to speed up the next run of the script, a created cache-file would hold the gathered died-dates (as they won't change too often...) and actors/actresses with a cached date, will not be fetched again from online sourced (until forced to by deleting the cache-file))

Too macabre to realize ? ;-D

P.S.
Examples for single* color:
normal actor image:
![bob normal](https://user-images.githubusercontent.com/96403800/170846182-1dbb231e-fa4f-4249-ad90-23fe54165563.jpg)
retro:
![bob retro-bw](https://user-images.githubusercontent.com/96403800/170846177-ad3fb2de-8295-4238-b471-ed008c549f8f.jpg)
sepia:
![bob sepia](https://user-images.githubusercontent.com/96403800/170846180-db3be2b8-6e31-4d8d-bbdb-f3c51602018d.jpg)

**Comment by Casvt** [comment]
This is such an interesting idea. The script will need to directly interact with the database of Plex because there is no api endpoint to change the picture of an actor. But I like a challenge :)

**Comment by JPH71** [comment]
I have managed to do this using your code to create empty collections.
there is a utility called thumbor that allows one to change a photo to grayscale.
You have to provide a link to your thumbor instance like
http://localhost:8888/unsafe/filters:grayscale()/<url to jpg>

you can read about it here: https://thumbor.readthedocs.io/en/latest/getting_started.html

I hope this helps

**Comment by Casvt** [comment]
By running such a service and then replacing the url in the database, you could make it work. But that's getting outside of the scope of "one-file that you run and done".

There is also the chance that the URL gets overridden when refreshing.

There also isn't really a reliable way to know if an actor has died or not.
