### ISSUE TITLE
Skip media if genre field is locked

### ISSUE THREAD

**Issue by Ark0301** [Casvt/Plex-scripts#88]
The keywords_to_genre script is working perfectly, but I have a suggestion for further functionality:

- Media will be skipped with no changes made if the genre field is locked
- Add an argument that will allow the script to edit media with a locked genre field

Thanks again

**Comment by Casvt** [comment]
> Media will be skipped with no changes made if the genre field is locked

This is easily doable
> Add an argument that will allow the script to edit media with a locked genre field

The script does this by default. It will "edit" every media item if needed, regardless of locked status. But with the argument mentioned at point one, you can reduce it to "edit" only media with the genre field unlocked.

**Comment by Ark0301** [comment]
That's right

**Comment by Casvt** [comment]
Request completed. Please redownload the script to get the new feature

**Comment by Ark0301** [comment]
Great stuff.
