### ISSUE TITLE
Add Shows/Movies from Discover tab in Plex

### ISSUE THREAD

**Issue by lamepennies** [Casvt/Plex-scripts#98]
Hello,
Since Plex added the Discover feature, I was thinking it'd be super cool to add shows/films that we want from that menu. 

I was thinking the script could look at what's in the watchlist and not in any libraries, add it to sonarr/radarr, then have an option to remove it from the watchlist or leave it there, and maybe add a collection tag as 'Discover' once added. If it's already added to sonarr/radarr and unreleased, it'll just add it to search for it. If it's already in the watchlist and with a 'Discover' tag, it'll ignore it.

**Comment by Casvt** [comment]
Cool idea. I can probably do this yeah.

**Comment by HStep20** [comment]
Sonarr/Radarr have this built in

**Comment by lamepennies** [comment]
Hey HStep, I just realized that was an added feature under lists. Thanks for the knowledge.
