### ISSUE TITLE
Easy Transfer Library to New Install

### ISSUE THREAD

**Issue by lamepennies** [Casvt/Plex-scripts#99]
Hello,
I was thinking of a more automated way to backup, transfer, and update a fresh install of plex that doesn't lose your info. I know Plex has [this guide](https://support.plex.tv/articles/201154537-move-media-content-to-a-new-location/) but I'm sure you can make it better. Was thinking of having an option to designate a backup location so you can use it for offsite and then an option to restore to a new plex server.

**Comment by Casvt** [comment]
You could've done a bit of a search through the repo before asking this. There are multiple scripts already made for this:

- [plex_exporter_importer.py](https://github.com/Casvt/Plex-scripts/blob/main/multiple_servers/plex_exporter_importer.py) Export and import plex metadata. There already is a feature request made for this script to allow the file not to be placed along side the media but instead just in a selected folder.
- [plex_sync.py](https://github.com/Casvt/Plex-scripts/blob/main/multiple_servers/plex_sync.py) Sync two plex servers that are on at the same time

**Comment by lamepennies** [comment]
Sorry but I took those as piecemeal thing, not for an entire library/server.

**Comment by Casvt** [comment]
Oh okay. Well they both do complete servers
